Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2018-07, with the labels that each got.

#1407 [IMPROVEMENT] Added text and description fields for Image Attachment
  app/src/main/java/chat/rocket/android/chatroom/adapter/ImageAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/ImageAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/res/layout/message_attachment.xml
Labels: :+1: improvement

#1249 [NEW] Android draw
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/domain/UriInteractor.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/helper/ImageHelper.kt
  app/src/main/res/drawable/ic_gesture_black_24dp.xml
  app/src/main/res/layout/message_attachment_options.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
  draw/.gitignore
  draw/build.gradle
  draw/proguard-rules.pro
  draw/src/main/AndroidManifest.xml
  draw/src/main/java/chat/rocket/android/draw/DrawingActivity.kt
  draw/src/main/java/chat/rocket/android/draw/widget/Action.kt
  draw/src/main/java/chat/rocket/android/draw/widget/CustomDrawView.kt
  draw/src/main/java/chat/rocket/android/draw/widget/Line.kt
  draw/src/main/java/chat/rocket/android/draw/widget/Move.kt
  draw/src/main/java/chat/rocket/android/draw/widget/MyPath.kt
  draw/src/main/java/chat/rocket/android/draw/widget/PaintOptions.kt
  draw/src/main/java/chat/rocket/android/draw/widget/Quad.kt
  draw/src/main/res/drawable/circle_black.xml
  draw/src/main/res/drawable/circle_blue.xml
  draw/src/main/res/drawable/circle_brown.xml
  draw/src/main/res/drawable/circle_green.xml
  draw/src/main/res/drawable/circle_pink.xml
  draw/src/main/res/drawable/circle_red.xml
  draw/src/main/res/drawable/circle_yellow.xml
  draw/src/main/res/drawable/ic_adjust_black_24dp.xml
  draw/src/main/res/drawable/ic_close_black_24dp.xml
  draw/src/main/res/drawable/ic_color_lens_black_24dp.xml
  draw/src/main/res/drawable/ic_eraser_black_24dp.xml
  draw/src/main/res/drawable/ic_opacity_black_24dp.xml
  draw/src/main/res/drawable/ic_redo_black_24dp.xml
  draw/src/main/res/drawable/ic_send_black_24dp.xml
  draw/src/main/res/drawable/ic_undo_black_24dp.xml
  draw/src/main/res/layout/activity_drawing.xml
  draw/src/main/res/layout/color_palette_view.xml
  draw/src/main/res/values/colors.xml
  draw/src/main/res/values/strings.xml
  settings.gradle
Labels: 🎉 feature

#1387 [NEW] Send message with attachments
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/res/drawable/rounded_color_accent.xml
  app/src/main/res/layout/file_attachments_dialog.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-uk-rRU/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1451 [FIX] Fix Reply with attachment
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#1438 [FEATURE] DB Spotlight + fixes
  app/build.gradle
  app/schemas/chat.rocket.android.db.RCDatabase/3.json
  app/src/main/java/chat/rocket/android/chatrooms/adapter/LoadingItemHolder.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/LoadingViewHolder.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomUiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomViewHolder.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomsAdapter.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/model/RoomUiModel.kt
  app/src/main/java/chat/rocket/android/chatrooms/di/ChatRoomsFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatrooms/domain/FetchChatRoomsInteractor.kt
  app/src/main/java/chat/rocket/android/chatrooms/infrastructure/ChatRoomsRepository.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsView.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
  app/src/main/java/chat/rocket/android/db/ChatRoomDao.kt
  app/src/main/java/chat/rocket/android/db/DatabaseManager.kt
  app/src/main/java/chat/rocket/android/db/model/ChatRoomEntity.kt
  app/src/main/java/chat/rocket/android/infrastructure/LocalRepository.kt
  app/src/main/java/chat/rocket/android/infrastructure/SharedPreferencesLocalRepository.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainView.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManagerFactory.kt
  app/src/main/java/chat/rocket/android/util/HttpLoggingInterceptor.kt
  app/src/main/java/chat/rocket/android/util/IO.kt
  app/src/main/java/chat/rocket/android/util/livedata/WrappedLiveData.kt
  app/src/main/java/chat/rocket/android/widget/DividerItemDecoration.kt
  app/src/main/res/layout/item_loading.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-uk-rRU/strings.xml
  app/src/main/res/values/strings.xml
  dependencies.gradle
Labels: :+1: improvement, :bug: bug, 🎉 feature

#1446 [IMPROVEMENT] Added project improvements.
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt
  app/src/main/java/chat/rocket/android/authentication/resetpassword/presentation/ResetPasswordPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/signup/presentation/SignupPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/domain/UriInteractor.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Attachment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/createchannel/presentation/CreateChannelPresenter.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/favoritemessages/presentation/FavoriteMessagesPresenter.kt
  app/src/main/java/chat/rocket/android/files/presentation/FilesPresenter.kt
  app/src/main/java/chat/rocket/android/main/di/MainModule.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/members/presentation/MembersPresenter.kt
  app/src/main/java/chat/rocket/android/mentions/presentention/MentionsPresenter.kt
  app/src/main/java/chat/rocket/android/pinnedmessages/presentation/PinnedMessagesPresenter.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/server/presentation/ChangeServerPresenter.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
  app/src/main/java/chat/rocket/android/settings/password/presentation/PasswordPresenter.kt
  app/src/main/java/chat/rocket/android/util/extensions/Image.kt
  build.gradle
  core/.gitignore
  core/build.gradle
  core/proguard-rules.pro
  core/src/main/AndroidManifest.xml
  core/src/main/java/chat/rocket/android/core/lifecycle/CancelStrategy.kt
  core/src/main/res/values/strings.xml
  dependencies.gradle
  draw/build.gradle
  draw/src/main/AndroidManifest.xml
  draw/src/main/java/chat/rocket/android/draw/DrawApplication.kt
  draw/src/main/java/chat/rocket/android/draw/dagger/AppComponent.kt
  draw/src/main/java/chat/rocket/android/draw/dagger/module/ActivityBuilderModule.kt
  draw/src/main/java/chat/rocket/android/draw/main/di/DrawModule.kt
  draw/src/main/java/chat/rocket/android/draw/main/presenter/DrawPresenter.kt
  draw/src/main/java/chat/rocket/android/draw/main/presenter/DrawView.kt
  draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
  draw/src/main/java/chat/rocket/android/draw/widget/Action.kt
  draw/src/main/res/layout/activity_drawing.xml
  draw/src/main/res/values/strings.xml
  settings.gradle
  util/.gitignore
  util/build.gradle
  util/proguard-rules.pro
  util/src/main/AndroidManifest.xml
  util/src/main/java/chat/rocket/android/util/extension/Coroutines.kt
  util/src/main/java/chat/rocket/android/util/extension/Image.kt
  util/src/main/res/values/strings.xml
Labels: :+1: improvement, :wrench: refactor

#1437 [NEW] Notify new message in the chat room.
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/res/drawable/round_textview.xml
  app/src/main/res/layout/message_list.xml
Labels: :lollipop: contrib: intermediate, 🎉 feature, 🖼 ux

#1469 [FIX] Custom OAuth url
  app/src/main/java/chat/rocket/android/helper/OauthHelper.kt
Labels: :bug: bug

#1481 [IMPROVEMENT] Connecting view at top of the chat list
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_chat_rooms.xml
Labels: :+1: improvement, 🖼 ux

#1426 [IMPROVEMENT] Choose default skin tone for emoji
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/util/extensions/Text.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-uk-rRU/strings.xml
  app/src/main/res/values/strings.xml
  emoji/build.gradle
  emoji/src/main/java/chat/rocket/android/emoji/CategoryPagerAdapter.kt
  emoji/src/main/java/chat/rocket/android/emoji/ComposerEditText.kt
  emoji/src/main/java/chat/rocket/android/emoji/Emoji.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiKeyboardPopup.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiParser.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiPickerPopup.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiRepository.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiTypefaceSpan.kt
  emoji/src/main/java/chat/rocket/android/emoji/Fitzpatrick.kt
  emoji/src/main/java/chat/rocket/android/emoji/internal/EmojiCategory.kt
  emoji/src/main/java/chat/rocket/android/emoji/internal/EmojiPagerAdapter.kt
  emoji/src/main/java/chat/rocket/android/emoji/internal/Preferences.kt
  emoji/src/main/res/drawable/color_change_circle.xml
  emoji/src/main/res/layout-land/emoji_picker.xml
  emoji/src/main/res/layout/color_select_popup.xml
  emoji/src/main/res/layout/emoji_keyboard.xml
  emoji/src/main/res/layout/emoji_row_item.xml
  emoji/src/main/res/values/colors.xml
  emoji/src/main/res/values/strings.xml
  emoji/src/main/res/values/styles.xml
Labels: :+1: improvement

#1480 [NEW] Search message
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Dialog.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
  app/src/main/java/chat/rocket/android/chatrooms/di/ChatRoomsFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/createchannel/ui/CreateChannelFragment.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/settings/password/ui/PasswordFragment.kt
  app/src/main/java/chat/rocket/android/util/livedata/WrappedLiveData.kt
  app/src/main/res/drawable/ic_search_white_24dp.xml
  app/src/main/res/menu/chatrooms.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-uk-rRU/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  util/build.gradle
  util/src/main/java/chat/rocket/android/util/extension/Rx.kt
  util/src/main/java/chat/rocket/android/util/extension/Widget.kt
Labels: 🎉 feature

#1487 [FIX] Noop'ing ordered list
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  app/src/main/res/layout/item_message.xml
  dependencies.gradle
Labels: :bug: bug

#1488 [i18n] Improvements in Russian translation
  app/src/main/res/values-uk-rRU/strings.xml
Labels: :earth_americas: i18n

#1496 [I18N] A few more spanish translations
  app/src/main/res/values-es/strings.xml
Labels: :earth_americas: i18n

#1501 [FIX] fix fullname on chatrooms
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomUiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/model/RoomUiModel.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
Labels: :bug: bug

#1509 [FIX] fix crashes 2.5.0 beta
  app/src/main/java/chat/rocket/android/chatrooms/domain/FetchChatRoomsInteractor.kt
  app/src/main/java/chat/rocket/android/db/DatabaseManager.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/res/layout/activity_add_members.xml
  app/src/main/res/layout/item_read_receipt.xml
  app/src/main/res/layout/layout_toolbar.xml
Labels: :bug: bug

#1510 [FIX] Improvements on the chatrooms list
  app/schemas/chat.rocket.android.db.RCDatabase/5.json
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomUiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/model/RoomUiModel.kt
  app/src/main/java/chat/rocket/android/chatrooms/di/ChatRoomsFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatrooms/domain/FetchChatRoomsInteractor.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/db/ChatRoomDao.kt
  app/src/main/java/chat/rocket/android/db/DatabaseManager.kt
  app/src/main/java/chat/rocket/android/db/RCDatabase.kt
  app/src/main/java/chat/rocket/android/db/UserDao.kt
  app/src/main/java/chat/rocket/android/db/model/ChatRoomEntity.kt
  app/src/main/java/chat/rocket/android/infrastructure/LocalRepository.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/server/domain/GetCurrentUserInteractor.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
  dependencies.gradle
Labels: :bug: bug

#1503 [NEW] Adds onboarding icon
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/res/drawable/ic_onboarding.xml
  app/src/main/res/values-es/strings.xml
Labels: :art: layout

#845 [NEW] Add day marker in chatroom
  app/src/main/java/chat/rocket/android/app/DateTimeHelper.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/AudioAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/AuthorAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/BaseUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/ColorAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/GenericFileAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/ImageAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/MessageAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/MessageReplyUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/MessageUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UrlPreviewUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/VideoAttachmentUiModel.kt
  app/src/main/res/layout/item_message.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-uk-rRU/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/fonts.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🎉 feature

#1500 [FIX] Typing status appearing for the current logged in user.
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-uk-rRU/strings.xml
  app/src/main/res/values/strings.xml
  draw/src/main/res/layout/activity_drawing.xml
Labels: :bug: bug

#1513 [I18n] Russian languague support
  app/src/main/res/values-ru/strings.xml
Labels: :earth_americas: i18n

#1515 [FIX] More fixes for 2.5.0 release
  app/src/main/java/chat/rocket/android/chatroom/ui/bottomsheet/MessageActionsBottomSheet.kt
  app/src/main/java/chat/rocket/android/db/DatabaseManager.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/server/domain/RefreshSettingsInteractor.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/java/chat/rocket/android/util/extensions/String.kt
Labels: :bug: bug

#1516 [i18n] Improvements in Russian translation
  app/src/main/res/values-ru/strings.xml
Labels: :earth_americas: i18n

#1519 [FIX] fix temporary status on reconnection
  app/src/main/java/chat/rocket/android/app/AppLifecycleObserver.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
Labels: :bug: bug

#1534 [IMPROVEMENT] Change date format
  app/src/main/java/chat/rocket/android/app/DateTimeHelper.kt
Labels: :+1: improvement

#1528 [NEW] German language support
  app/src/main/res/values-de/strings.xml
Labels: :earth_americas: i18n

#1540 [FIX] Fix cast exception when parsing an OrderedList object
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
Labels: :bug: bug, :clock1: regression

#1543 [FIX] fix crash uninitialized adapter
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/favoritemessages/ui/FavoriteMessagesFragment.kt
  app/src/main/java/chat/rocket/android/mentions/ui/MentionsFragment.kt
  app/src/main/java/chat/rocket/android/pinnedmessages/ui/PinnedMessagesFragment.kt
Labels: :bug: bug

#1544 [FIX] fix typing status for 2.5.1
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/res/values-es/strings.xml
  core/build.gradle
Labels: :bug: bug

#1548 [FIX] Fix uppercase url scheme
  app/src/main/java/chat/rocket/android/chatroom/adapter/UrlPreviewViewHolder.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  app/src/main/java/chat/rocket/android/util/extensions/String.kt
  app/src/main/java/chat/rocket/android/util/extensions/View.kt
Labels: :bug: bug

#1551 [FIX] fix auth deeplink
  app/src/main/java/chat/rocket/android/authentication/domain/model/LoginDeepLinkInfo.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/authentication/ui/AuthenticationActivity.kt
Labels: :bug: bug

#1550 [FIX] Opened notifications not cleared
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/push/GroupedPush.kt
  app/src/main/java/chat/rocket/android/push/PushManager.kt
Labels: :bug: bug

#1553 [NEW] WordPress Oauth login support
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/helper/OauthHelper.kt
  app/src/main/java/chat/rocket/android/server/domain/RefreshSettingsInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SettingsRepository.kt
  app/src/main/res/drawable/ic_wordpress.xml
  app/src/main/res/layout/fragment_authentication_log_in.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-uk-rRU/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1554 [IMPROVEMENT] More idiomatic kotlin
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
Labels: :wrench: refactor

#1555 [FIX] Check if we are in a RESUMED state before showing the Dialog.
  app/src/main/java/chat/rocket/android/chatroom/adapter/BaseViewHolder.kt
Labels: :bug: bug

#1558 [HOTFIX] Ordered list should iterate over its direct child first
  app/build.gradle
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
Labels: :bug: bug
