Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2018-11, with the labels that each got.

#1817 [FIX][IMPROVEMENT] CAS button not showing and CAS button style
  app/src/main/java/chat/rocket/android/authentication/loginoptions/presentation/LoginOptionsView.kt
  app/src/main/java/chat/rocket/android/authentication/loginoptions/ui/LoginOptionsFragment.kt
  app/src/main/java/chat/rocket/android/authentication/onboarding/presentation/OnBoardingPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/presentation/AuthenticationNavigator.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerPresenter.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
  app/src/main/res/layout/fragment_authentication_login_options.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: :+1: improvement, :bug: bug

#1819 Update strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#1835 [RELEASE] 3.1.1 hotfix
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :rocket: release:master

#1841 [NEW] Add share app
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/defaults.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1844 [NEW] Adds delete own account.
  app/src/main/ic_launcher-web.png
  app/src/main/java/chat/rocket/android/authentication/onboarding/presentation/OnBoardingPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainView.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfileView.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
  app/src/main/java/chat/rocket/android/server/presentation/TokenView.kt
  app/src/main/res/menu/action_mode_profile.xml
  app/src/main/res/menu/profile.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
  util/src/main/java/chat/rocket/android/util/extension/Text.kt
Labels: 🎉 feature

#1837 [NEW] Rate app on playstore
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/defaults.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1790 [NEW] Adds analytics for reset password event.
  app/schemas/chat.rocket.android.db.RCDatabase/12.json
  app/src/main/java/chat/rocket/android/analytics/Analytics.kt
  app/src/main/java/chat/rocket/android/analytics/AnalyticsManager.kt
  app/src/main/java/chat/rocket/android/settings/password/presentation/PasswordPresenter.kt
  app/src/play/java/chat/rocket/android/analytics/AnswersAnalytics.kt
  app/src/play/java/chat/rocket/android/analytics/GoogleAnalyticsForFirebase.kt
Labels: :+1: improvement

#1864 [I18N] Add locale italian
  app/src/main/res/values-it/strings.xml
Labels: :earth_americas: i18n

#1852 [NEW] Take a photo
  app/src/debug/res/xml/file_paths.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/res/layout/message_attachment_options.xml
  app/src/main/res/layout/update_avatar_options.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/file_paths.xml
  util/src/main/java/chat/rocket/android/util/extension/Image.kt
Labels: 🎉 feature

#1855 [IMPROVEMENT] Avoid typing domain and TLD
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
Labels: :+1: improvement, 🖼 ux

#1860 [NEW] Observe channel changes
  app/src/main/java/chat/rocket/android/chatroom/di/ChatRoomFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomUiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/model/RoomUiModel.kt
  app/src/main/java/chat/rocket/android/chatrooms/di/ChatRoomsFragmentModule.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
Labels: :+1: improvement

#1861 [FIX] Emoji skin tone chooser dialog showing invalid characters
  emoji/src/main/java/chat/rocket/android/emoji/EmojiKeyboardPopup.kt
  emoji/src/main/res/drawable/bg_skin_tone.xml
  emoji/src/main/res/layout/color_select_popup.xml
  emoji/src/main/res/layout/dialog_skin_tone_chooser.xml
  emoji/src/main/res/layout/emoji_keyboard.xml
Labels: :bug: bug

#1863 [FIX] Username not being displayed.
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
Labels: :bug: bug

#1866 [FIX] Do not clear the composer when enabling the send message button
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#1882 [FIX] Don't log to console on Production builds
  app/src/foss/java/chat/rocket/android/helper/CrashlyticsTree.kt
  app/src/play/java/chat/rocket/android/helper/CrashlyticsTree.kt
Labels: :bug: bug

#1879 [IMPROVEMENT] Take a photo icon.
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/layout/message_attachment_options.xml
Labels: :+1: improvement, :art: layout

#1880 [FIX] Layout fixes and Room refresh fix
  app/src/main/java/chat/rocket/android/chatroom/adapter/AttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/db/DatabaseManager.kt
  app/src/main/res/layout/item_message.xml
Labels: :+1: improvement

#1877 [FIX] onbording being cut off on some resolutions.
  app/src/main/res/layout/fragment_authentication_on_boarding.xml
Labels: :art: layout, :bug: bug
