Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2018-02, with the labels that each got.

#736 [DOCS] Build details in README.md
  README.md
Labels: docs

#746 [FIX] SVG rendering improvements
  app/build.gradle
  app/src/main/java/chat/rocket/android/app/DrawableHelper.kt
  app/src/main/java/chat/rocket/android/app/utils/SvgDecoder.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/res/layout/avatar.xml
  app/src/main/res/layout/item_chat.xml
  build.gradle
  dependencies.gradle
Labels: improvement

#750 [FIX] Improve file upload
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/domain/UriInteractor.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/server/domain/RefreshSettingsInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SettingsRepository.kt
  app/src/main/java/chat/rocket/android/util/extensions/Collections.kt
  app/src/main/java/chat/rocket/android/util/extensions/Text.kt
  app/src/main/java/chat/rocket/android/util/extensions/Uri.kt
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: improvement

#776 [NEW][FIX] Prevents losing all entered text when a new message arrives on the chat
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/java/chat/rocket/android/util/extensions/Animation.kt
  app/src/main/java/chat/rocket/android/util/extensions/Ui.kt
  app/src/main/res/drawable/ic_arrow_downward_24dp.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/layout/message_list.xml
  app/src/main/res/layout/unread_messages_badge.xml
Labels: feature, improvement

#785 [Chore][FIX] Update dependencies
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/helper/CrashlyticsTree.kt
  dependencies.gradle
Labels: chore, urgent

#794 [FIX] Layout improvements
  app/build.gradle
  app/src/main/java/chat/rocket/android/authentication/login/di/LoginFragmentProvider.kt
  app/src/main/java/chat/rocket/android/authentication/presentation/AuthenticationNavigator.kt
  app/src/main/java/chat/rocket/android/authentication/server/di/ServerFragmentProvider.kt
  app/src/main/java/chat/rocket/android/chatroom/di/PinnedMessagesFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsView.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  app/src/main/java/chat/rocket/android/main/di/MainActivityModule.kt
  app/src/main/java/chat/rocket/android/main/di/MainActivityProvider.kt
  app/src/main/java/chat/rocket/android/main/di/MainModule.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainNavigator.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainView.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/util/extensions/Animation.kt
  app/src/main/java/chat/rocket/android/widget/DividerItemDecoration.kt
  app/src/main/res/anim/close_enter.xml
  app/src/main/res/anim/close_exit.xml
  app/src/main/res/anim/open_enter.xml
  app/src/main/res/anim/open_exit.xml
  app/src/main/res/drawable/ic_exit_to_app_black_24dp.xml
  app/src/main/res/drawable/ic_settings_black_24dp.xml
  app/src/main/res/drawable/style_message_file_upload_content_bg.xml
  app/src/main/res/drawable/style_message_file_upload_layout_bg.xml
  app/src/main/res/layout/fragment_authentication_log_in.xml
  app/src/main/res/layout/fragment_authentication_server.xml
  app/src/main/res/layout/fragment_authentication_sign_up.xml
  app/src/main/res/layout/fragment_authentication_two_fa.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/message_attachment.xml
  app/src/main/res/layout/unread_messages_badge.xml
  app/src/main/res/menu/chatrooms.xml
  app/src/main/res/menu/navigation.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  dependencies.gradle
Labels: layout

#804 [NEW] Mark room as read.
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
Labels: feature, improvement

#807 [FIX] Allow colon(:) in server url
  app/src/main/res/layout/fragment_authentication_server.xml
Labels: improvement
