Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2018-04, with the labels that each got.

#992 [IMPROVEMENT] Navigate to profile on click on avatar
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
Labels: :+1: improvement

#996 [NEW] Update app icon.
  app/src/main/ic_launcher-web.png
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
Labels: :art: layout

#998 [FIX] Show TwoFA screen if TOPT is required.
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
Labels: :bug: bug

#999 [NEW] Version check
  app/build.gradle
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/VersionCheckView.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainView.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
  app/src/main/java/chat/rocket/android/util/VersionInfo.kt
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
  dependencies.gradle
Labels: 🎉 feature

#1003 [FIX] Alerts the user about username creation using the web version.
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: :bug: bug

#993 [CHORE] Increment version to beta1 & 2001
  app/build.gradle
Labels: :rocket: release:beta, :truck: chore

#1013 [CHORE] Increment version to beta2
  app/build.gradle
Labels: :rocket: release:beta

#1014 [FIX] Don't crash on missing Play Services.
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/push/FirebaseTokenService.kt
Labels: :bug: bug

#1015 [NEW] Add register username screen
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/presentation/AuthenticationNavigator.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/di/RegisterUsernameFragmentModule.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/di/RegisterUsernameFragmentProvider.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernameView.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/ui/RegisterUsernameFragment.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/ui/TwoFAFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/util/extensions/Ui.kt
  app/src/main/res/layout/fragment_authentication_register_username.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1016 [CHORE] Increment version to beta 3
  app/build.gradle
Labels: :rocket: release:beta

#1017 [FIX] Blank screen.
  app/src/main/java/chat/rocket/android/authentication/presentation/AuthenticationPresenter.kt
Labels: :bug: bug

#1024 [IMPROVEMENT] Keep message on the text composer on fail to send message
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/res/values-pt-rBR/strings.xml
Labels: :+1: improvement

#1026 [NEW] Add the possibility to change own status.
  app/src/main/java/chat/rocket/android/app/DrawableHelper.kt
  app/src/main/java/chat/rocket/android/main/adapter/AccountViewHolder.kt
  app/src/main/java/chat/rocket/android/main/adapter/AccountsAdapter.kt
  app/src/main/java/chat/rocket/android/main/adapter/StatusViewHolder.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainView.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/res/drawable/black_gradient.xml
  app/src/main/res/drawable/ic_status_away_24dp.xml
  app/src/main/res/drawable/ic_status_busy_24dp.xml
  app/src/main/res/drawable/ic_status_invisible_24dp.xml
  app/src/main/res/drawable/ic_status_online_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_account.xml
  app/src/main/res/layout/item_add_account.xml
  app/src/main/res/layout/item_change_status.xml
  app/src/main/res/layout/nav_header.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1031 [CHORE] Increment build beta number to 4
  app/build.gradle
Labels: :rocket: release:beta

#1033 [CHORE] Increment versionCode
  app/build.gradle
Labels: :rocket: release:beta

#1034 [IMPROVEMENT] Get own current status (REST).
  app/src/main/java/chat/rocket/android/app/DrawableHelper.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainView.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/main/viewmodel/NavHeaderViewModel.kt
  app/src/main/java/chat/rocket/android/main/viewmodel/NavHeaderViewModelMapper.kt
  app/src/main/res/layout/nav_header.xml
Labels: :+1: improvement

#1036 [CHORE] Increment versionCode to 2006
  app/build.gradle
Labels: :rocket: release:beta

#1041 [FIX] Broken swype by removing the re-enable suggestions code
  app/src/main/java/chat/rocket/android/widget/autocompletion/ui/SuggestionsView.kt
Labels: :bug: bug

#1042 [CHORE] Increment build version to beta5
  app/build.gradle
Labels: :rocket: release:beta

#1000 [DOCS] Creates a initial version of our planning document
  PLANNING.md
Labels: :memo: docs

#1058 [FIX] Remove the check for internet connection.
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernameView.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/ui/RegisterUsernameFragment.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerView.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/authentication/signup/presentation/SignupPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/signup/presentation/SignupView.kt
  app/src/main/java/chat/rocket/android/authentication/signup/ui/SignupFragment.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAView.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/ui/TwoFAFragment.kt
  app/src/main/java/chat/rocket/android/core/behaviours/InternetView.kt
  app/src/main/java/chat/rocket/android/helper/NetworkHelper.kt
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: :bug: bug, 🔥 urgent

#1061 [CHORE] Increment version of the app to Beta 6
  app/build.gradle
Labels: :rocket: release:beta

#1064 [FIX] Avatar URL for channels and groups.
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/java/chat/rocket/android/members/viewmodel/MemberViewModel.kt
  app/src/main/java/chat/rocket/android/util/extensions/String.kt
Labels: :+1: improvement

#1069 [NEW] Add listen to updates on own profile.
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/main/viewmodel/NavHeaderViewModel.kt
  app/src/main/java/chat/rocket/android/main/viewmodel/NavHeaderViewModelMapper.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
  app/src/main/java/chat/rocket/android/settings/password/presentation/PasswordPresenter.kt
  build.gradle
Labels: 🎉 feature

#781 [FIX] Build instruction for develop-2.x branch
  README.md
Labels: :memo: docs

#1074 [FIX] always run view callbacks on ui thread
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/ui/RegisterUsernameFragment.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/authentication/signup/ui/SignupFragment.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/ui/TwoFAFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/PinnedMessagesFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/members/presentation/MembersNavigator.kt
  app/src/main/java/chat/rocket/android/members/ui/MemberBottomSheetFragment.kt
  app/src/main/java/chat/rocket/android/members/ui/MembersFragment.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
  app/src/main/java/chat/rocket/android/settings/password/ui/PasswordFragment.kt
  app/src/main/java/chat/rocket/android/util/extensions/Fragment.kt
  app/src/main/res/layout/item_chat.xml
Labels: :bug: bug

#797 [IMPROVEMENT] networkSecurityConfig for API 24+ to allow user imported root CAs as trust anchors
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/network_security_config.xml
Labels: :+1: improvement

#1066 [NEW] No pinned message shown on empty pin List
  app/src/main/java/chat/rocket/android/chatroom/ui/PinnedMessagesFragment.kt
  app/src/main/res/drawable/ic_pin_black_24dp.xml
  app/src/main/res/layout/fragment_pinned_messages.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: :+1: improvement

#1072 [PROJECT] Change SDK imports.
  app/src/main/java/chat/rocket/android/app/DrawableHelper.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsView.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/main/adapter/AccountsAdapter.kt
  app/src/main/java/chat/rocket/android/main/adapter/StatusViewHolder.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainView.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
Labels: :truck: chore

#1081 [NEW] ColorAttachment (need a better name)
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ColorAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/BaseViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ColorAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/res/layout/item_color_attachment.xml
Labels: 🎉 feature

#1080 [CHORE] Increment version code to 2.0.0-rc1
  app/build.gradle
Labels: :rocket: release:beta

#1093 [NEW] Auth deep link
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/authentication/domain/model/LoginDeepLinkInfo.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/presentation/AuthenticationNavigator.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/ui/TwoFAFragment.kt
  app/src/main/java/chat/rocket/android/authentication/ui/AuthenticationActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/core/behaviours/MessageView.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/server/domain/RefreshSettingsInteractor.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
Labels: 🎉 feature

#1094 [RELEASE] Prepare the app for final 2.0.0 release
  app/build.gradle
Labels: :rocket: release:master

#1098 [FIX] Fixes for 2.0.0
  app/build.gradle
  app/src/main/java/chat/rocket/android/authentication/domain/model/LoginDeepLinkInfo.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/push/FirebaseTokenService.kt
Labels: :bug: bug

#1121 [HOTFIX] Move version check to server screen
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerView.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/VersionCheckView.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/authentication/ui/AuthenticationActivity.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
Labels: :bug: bug

#1107 [FIX] Fixes for 2.0.1
  app/src/main/java/chat/rocket/android/chatroom/di/ChatRoomFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatroom/di/ChatRoomModule.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfileView.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/server/ui/ChangeServerActivity.kt
Labels: :bug: bug

#1125 [FIX] Fixes for the 2.0.2 hotfix
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
Labels: :bug: bug

#1123 [CHORE] Prepare the app to hotfix 2.0.2
  app/build.gradle
Labels: :rocket: release:master

#1126 [NEW] Facebook oauth login
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/helper/OauthHelper.kt
Labels: 🎉 feature

#1124 [DOCS] Improve a little bit our issue template
  .github/ISSUE_TEMPLATE.md
Labels: :memo: docs

#1128 [RELEASE] Merge beta into master
  .github/ISSUE_TEMPLATE.md
  app/build.gradle
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerView.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/VersionCheckView.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/authentication/ui/AuthenticationActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/di/ChatRoomFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatroom/di/ChatRoomModule.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/helper/OauthHelper.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfileView.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
  app/src/main/java/chat/rocket/android/server/ui/ChangeServerActivity.kt
Labels: :rocket: release:master

#1140 [IMPROVEMENT] Only allow Openable content in Storage Access Framework
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :+1: improvement

#1156 [RELEASE] Merge develop into master
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/authentication/server/presentation/VersionCheckView.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
  app/src/main/java/chat/rocket/android/util/extensions/String.kt
  app/src/main/res/layout/fragment_authentication_server.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: :rocket: release:master

#1155 [CHORE] Increment version of the app to release 2.0.3
  app/build.gradle
Labels: :rocket: release:master

#1157 [RELEASE] Update master from develop
  app/build.gradle
Labels: :rocket: release:master

#1163 [DOCS] Update README removing v1 references
  README.md
Labels: :memo: docs

#1165 [FIX] setting.oauth
  app/build.gradle
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/webview/oauth/ui/OauthWebViewActivity.kt
Labels: :bug: bug

#1168 [RELEASE] Merge develop into master
  README.md
  app/build.gradle
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/webview/oauth/ui/OauthWebViewActivity.kt
Labels: :rocket: release:master

#1108 [NEW] Show user status in the chat list.
  app/build.gradle
  app/src/main/java/chat/rocket/android/app/DrawableHelper.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/server/domain/ActiveUsersRepository.kt
  app/src/main/java/chat/rocket/android/server/domain/GetActiveUsersInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/GetChatRoomsInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SaveActiveUsersInteractor.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/MemoryActiveUsersRepository.kt
  app/src/main/res/drawable/ic_hashtag_12dp.xml
  app/src/main/res/drawable/ic_lock_12_dp.xml
  app/src/main/res/drawable/ic_status_away_12dp.xml
  app/src/main/res/drawable/ic_status_away_24dp.xml
  app/src/main/res/drawable/ic_status_busy_12dp.xml
  app/src/main/res/drawable/ic_status_busy_24dp.xml
  app/src/main/res/drawable/ic_status_invisible_12dp.xml
  app/src/main/res/drawable/ic_status_invisible_24dp.xml
  app/src/main/res/drawable/ic_status_online_12dp.xml
  app/src/main/res/drawable/ic_status_online_24dp.xml
  app/src/main/res/drawable/user_status_white.xml
  app/src/main/res/layout/fragment_chat_rooms.xml
  app/src/main/res/layout/item_change_status.xml
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/layout/nav_header.xml
  app/src/main/res/layout/suggestion_member_item.xml
  app/src/main/res/layout/suggestion_room_item.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values/dimens.xml
Labels: 🎉 feature

#1136 [IMPROVEMENT] Set temporary status
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/app/AppLifecycleObserver.kt
  app/src/main/java/chat/rocket/android/app/RocketChatApplication.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/PinnedMessagesPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/dagger/AppComponent.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/members/presentation/MembersPresenter.kt
  app/src/main/java/chat/rocket/android/members/ui/MembersFragment.kt
  app/src/main/java/chat/rocket/android/settings/about/ui/AboutActivity.kt
  app/src/main/java/chat/rocket/android/settings/password/presentation/PasswordPresenter.kt
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
  dependencies.gradle
Labels: :+1: improvement

#1179 [FIX] Adds double check before showing the sign up view.
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
Labels: :bug: bug

#1171 [TESTS] Restore unit tests
  .circleci/config.yml
  app/src/test/java/chat/rocket/android/MemoryMessagesRepositoryTest.kt
Labels: :white_check_mark: tests

#1187 [I18N] Add Spanish localization file
  app/src/main/res/values-es/strings.xml
Labels: :earth_americas: i18n

#1192 [I18N] Add French localization strings.xml file
  app/src/main/res/values-fr/strings.xml
Labels: :earth_americas: i18n

#1186 [I18N] Fixed typos in pt-BR translation
  app/src/main/res/values-pt-rBR/strings.xml
Labels: :earth_americas: i18n

#1198 [I18N] French translation (new PR)
  app/src/main/res/values-fr/strings.xml
Labels: :earth_americas: i18n

#1202 [FIX] Show more social account icon not showing
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/util/extensions/Ui.kt
Labels: :bug: bug

#1194 [NEW] Support to login using Custom OAuth
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/helper/OauthHelper.kt
  app/src/main/java/chat/rocket/android/util/extensions/String.kt
  app/src/main/java/chat/rocket/android/webview/oauth/ui/OauthWebViewActivity.kt
  build.gradle
  dependencies.gradle
Labels: 🎉 feature

#1204 [FIX] Use username when building replies always
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  dependencies.gradle
Labels: :bug: bug

#1167 [NEW] No chat message shown on empty chat list
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/res/drawable/ic_chat_black_24dp.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/message_composer.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1195 [NEW] Add GenericFileAttachment
  app/src/main/java/chat/rocket/android/app/RocketChatApplication.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/GenericFileAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/BaseViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/GenericFileAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/infrastructure/LocalRepository.kt
  app/src/main/java/chat/rocket/android/infrastructure/SharedPrefsLocalRepository.kt
  app/src/main/res/layout/item_author_attachment.xml
  app/src/main/res/layout/item_file_attachment.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1206 [NEW] Forgot password
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/presentation/AuthenticationNavigator.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/ui/RegisterUsernameFragment.kt
  app/src/main/java/chat/rocket/android/authentication/resetpassword/di/ResetPasswordFragmentModule.kt
  app/src/main/java/chat/rocket/android/authentication/resetpassword/di/ResetPasswordFragmentProvider.kt
  app/src/main/java/chat/rocket/android/authentication/resetpassword/presentation/ResetPasswordPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/resetpassword/presentation/ResetPasswordView.kt
  app/src/main/java/chat/rocket/android/authentication/resetpassword/ui/ResetPasswordFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/util/extensions/Ui.kt
  app/src/main/res/layout/fragment_authentication_log_in.xml
  app/src/main/res/layout/fragment_authentication_reset_password.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1207 [FIX] Use username when building replies always (update)
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
Labels: :bug: bug

#1196 [NEW] Implement save image to gallery
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/chatroom/adapter/ImageAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/helper/AndroidPermissionsHelper.kt
  app/src/main/res/drawable/ic_arrow_back_white_24dp.xml
  app/src/main/res/menu/image_actions.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1209 [FIX] Show real name instead of username on chat list
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
Labels: :bug: bug

#1219 [I18N] Correct grammar in sign in title
  app/src/main/res/values/strings.xml
Labels: :earth_americas: i18n

#1214 [IMPROVEMENT] Change OkHttpClient initialization in Dagger graph
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
Labels: :+1: improvement

#1212 [IMPROVEMENT] Change ImagePipelineConfig initialization in Dagger graph
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
Labels: :+1: improvement
