Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2018-12, with the labels that each got.

#1896 [FIX] Crash on reaction long press
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#1872 [NEW] User details screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/authentication/ui/AuthenticationActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/MessageUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/members/adapter/MembersAdapter.kt
  app/src/main/java/chat/rocket/android/members/presentation/MembersNavigator.kt
  app/src/main/java/chat/rocket/android/members/presentation/MembersPresenter.kt
  app/src/main/java/chat/rocket/android/members/uimodel/MemberUiModel.kt
  app/src/main/java/chat/rocket/android/members/uimodel/MemberUiModelMapper.kt
  app/src/main/java/chat/rocket/android/settings/password/ui/PasswordFragment.kt
  app/src/main/java/chat/rocket/android/userdetails/di/UserDetailsModule.kt
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsPresenter.kt
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsView.kt
  app/src/main/java/chat/rocket/android/userdetails/ui/UserDetailsActivity.kt
  app/src/main/java/chat/rocket/android/util/extensions/Graphics.kt
  app/src/main/java/chat/rocket/android/util/extensions/Ui.kt
  app/src/main/res/drawable/bg_round_bounds_white.xml
  app/src/main/res/drawable/ic_message_24dp.xml
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/layout/activity_user_details.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1903 [I18N] update IN strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
Labels: :earth_americas: i18n

#1890 [NEW] Redesign chat list.
  app/src/main/java/chat/rocket/android/chatroom/di/ChatRoomFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomUiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomViewHolder.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomsAdapter.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/model/RoomUiModel.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/SimpleSectionedRecyclerViewAdapter.kt
  app/src/main/res/drawable/ic_hashtag_unread_12dp.xml
  app/src/main/res/drawable/style_total_unread_messages.xml
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_message_attachment.xml
  app/src/main/res/layout/item_message_attachment_old.xml
  app/src/main/res/layout/unread_messages_badge.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  dependencies.gradle
Labels: :+1: improvement, :art: layout

#1873 [NEW] Report message
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/res/drawable/ic_action_message_report_24dp.xml
  app/src/main/res/layout/dialog_report.xml
  app/src/main/res/menu/message_actions.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1905 [FIX] Some usability adjustments
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageViewHolder.kt
  app/src/main/java/chat/rocket/android/db/UserDao.kt
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsPresenter.kt
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsView.kt
  app/src/main/java/chat/rocket/android/userdetails/ui/UserDetailsActivity.kt
  app/src/main/res/layout/activity_user_details.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: :bug: bug

#1910 [I18N] update IT strings.xml
  app/src/main/res/values-it/strings.xml
Labels: :earth_americas: i18n

#1928 [I18N] Add proper translation to italian strings
  app/src/main/res/values-it/strings.xml
Labels: :earth_americas: i18n

#1924 [I18N] update (IT) and (hi) strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
Labels: :earth_americas: i18n

#1916 [I18N] Update RU strings.xml v.2
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#1915 [FIX] RuntimeException bug.
  app/src/main/java/chat/rocket/android/settings/password/presentation/PasswordPresenter.kt
  app/src/main/java/chat/rocket/android/settings/password/ui/PasswordFragment.kt
  app/src/main/res/layout/fragment_password.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: :bug: bug

#1922 [Fix] Crash when creating channel
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/res/layout/dialog_report.xml
  app/src/main/res/layout/file_attachments_dialog.xml
  app/src/main/res/layout/fragment_authentication_log_in.xml
  app/src/main/res/layout/fragment_authentication_login_options.xml
  app/src/main/res/layout/fragment_authentication_register_username.xml
  app/src/main/res/layout/fragment_authentication_reset_password.xml
  app/src/main/res/layout/fragment_authentication_server.xml
  app/src/main/res/layout/fragment_authentication_sign_up.xml
  app/src/main/res/layout/fragment_authentication_two_fa.xml
  app/src/main/res/layout/item_message_reply.xml
  app/src/main/res/layout/message_attachment_options.xml
  app/src/main/res/layout/message_composer.xml
  app/src/main/res/layout/update_avatar_options.xml
  app/src/main/res/values/styles.xml
Labels: :art: layout, :bug: bug

#1931 [NEW] Renders all images formats on the chat room from an url link.
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  util/src/main/java/chat/rocket/android/util/extension/Url.kt
Labels: 🎉 feature

#1933 [FIX] Improve autocomplete speed
  suggestions/src/main/java/chat/rocket/android/suggestions/ui/SuggestionsAdapter.kt
  suggestions/src/main/java/chat/rocket/android/suggestions/ui/SuggestionsView.kt
Labels: :bug: bug

#1934 [I18N] Update RU strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#1937 [I18N] Update Hindi strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
Labels: :earth_americas: i18n

#1930 [FIX] roomid or username required bug
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsPresenter.kt
Labels: :bug: bug

#1946 [FIX] Increase db retries
  app/src/main/java/chat/rocket/android/util/IO.kt
Labels: :truck: chore

#1948 [IMPROVEMENT] Draft messages
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/infrastructure/LocalRepository.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
Labels: :+1: improvement

#1953 [FIX] Emoji keyboard
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/res/drawable/ic_keyboard_black_24dp.xml
  app/src/main/res/layout/message_composer.xml
  emoji/src/main/java/chat/rocket/android/emoji/EmojiKeyboardPopup.kt
  emoji/src/main/java/chat/rocket/android/emoji/OverKeyboardPopupWindow.kt
Labels: :bug: bug

#1932 [RELEASE] Merge DEVELOP into BETA
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/dagger/module/LocalModule.kt
  app/src/main/java/chat/rocket/android/infrastructure/LocalRepository.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/RocketChatClientFactory.kt
  app/src/main/java/chat/rocket/android/settings/password/presentation/PasswordPresenter.kt
  app/src/main/java/chat/rocket/android/settings/password/presentation/PasswordView.kt
  app/src/main/java/chat/rocket/android/settings/password/ui/PasswordFragment.kt
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsPresenter.kt
  app/src/main/java/chat/rocket/android/util/IO.kt
  app/src/main/java/chat/rocket/android/util/extensions/String.kt
  app/src/main/res/drawable/ic_keyboard_black_24dp.xml
  app/src/main/res/layout/dialog_report.xml
  app/src/main/res/layout/file_attachments_dialog.xml
  app/src/main/res/layout/fragment_authentication_log_in.xml
  app/src/main/res/layout/fragment_authentication_login_options.xml
  app/src/main/res/layout/fragment_authentication_register_username.xml
  app/src/main/res/layout/fragment_authentication_reset_password.xml
  app/src/main/res/layout/fragment_authentication_server.xml
  app/src/main/res/layout/fragment_authentication_sign_up.xml
  app/src/main/res/layout/fragment_authentication_two_fa.xml
  app/src/main/res/layout/fragment_password.xml
  app/src/main/res/layout/item_message_reply.xml
  app/src/main/res/layout/message_attachment_options.xml
  app/src/main/res/layout/message_composer.xml
  app/src/main/res/layout/update_avatar_options.xml
  app/src/main/res/menu/chatrooms.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  emoji/src/main/java/chat/rocket/android/emoji/EmojiKeyboardPopup.kt
  emoji/src/main/java/chat/rocket/android/emoji/OverKeyboardPopupWindow.kt
  suggestions/src/main/java/chat/rocket/android/suggestions/ui/SuggestionsAdapter.kt
  suggestions/src/main/java/chat/rocket/android/suggestions/ui/SuggestionsView.kt
  util/src/main/java/chat/rocket/android/util/extension/Url.kt
Labels: :rocket: release:beta

#1954 [i18N] Update RU strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#1964 [NEW][DOCS] Add Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: :memo: docs

#1966 [IMPROVEMENT] [DOCS] Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :memo: docs

#1969 [I18N] Add proper translation to italian strings for password update
  app/src/main/res/values-it/strings.xml
Labels: :earth_americas: i18n

#1967 [I18N] Update strings
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values/strings.xml
Labels: :earth_americas: i18n

#1975 [I18N] Added german translations
  app/src/main/res/values-de/strings.xml
Labels: :earth_americas: i18n
