Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2018-10, with the labels that each got.

#1702 [I18N] Added translation "msg_view_more", "msg_view_less'' in RU
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#1713 [PROJECT] Bump Android gradle plugin to 3.2.0 stable version
  build.gradle
Labels: :truck: chore

#1710 [I18N] Add turkish language support
  app/src/main/res/values-tr/strings.xml
Labels: :earth_americas: i18n

#1712 [FIX] Fix the logic to render multiple mentions to the same user
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
Labels: :bug: bug

#1669 [FEATURE] Initial message db support
  app/build.gradle
  app/schemas/chat.rocket.android.db.RCDatabase/6.json
  app/schemas/chat.rocket.android.db.RCDatabase/7.json
  app/schemas/chat.rocket.android.db.RCDatabase/8.json
  app/schemas/chat.rocket.android.db.RCDatabase/9.json
  app/sender-id.txt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ActionsListAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ColorAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/di/ChatRoomFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/service/MessageService.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/ColorAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/suggestion/ChatRoomSuggestionUiModel.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/db/BaseDao.kt
  app/src/main/java/chat/rocket/android/db/ChatRoomDao.kt
  app/src/main/java/chat/rocket/android/db/DatabaseManager.kt
  app/src/main/java/chat/rocket/android/db/MessageDao.kt
  app/src/main/java/chat/rocket/android/db/RCDatabase.kt
  app/src/main/java/chat/rocket/android/db/model/Attachments.kt
  app/src/main/java/chat/rocket/android/db/model/Messages.kt
  app/src/main/java/chat/rocket/android/db/model/Reactions.kt
  app/src/main/java/chat/rocket/android/db/model/Url.kt
  app/src/main/java/chat/rocket/android/server/domain/ActiveUsersRepository.kt
  app/src/main/java/chat/rocket/android/server/domain/GetActiveUsersInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/MessagesRepository.kt
  app/src/main/java/chat/rocket/android/server/domain/RoomRepository.kt
  app/src/main/java/chat/rocket/android/server/domain/SaveActiveUsersInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/model/Server.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/DatabaseMessageMapper.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/DatabaseMessagesRepository.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/MemoryActiveUsersRepository.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/MemoryMessagesRepository.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/MemoryRoomRepository.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesMessagesRepository.kt
  app/src/main/java/chat/rocket/android/util/extensions/Fragment.kt
  app/src/main/java/chat/rocket/android/util/extensions/RocketChatClient.kt
  app/src/main/res/layout/item_color_attachment.xml
  config/quality/quality.gradle
  emoji/src/main/java/chat/rocket/android/emoji/EmojiRepository.kt
  emoji/src/main/java/chat/rocket/android/emoji/OverKeyboardPopupWindow.kt
  util/src/main/java/chat/rocket/android/util/extension/Boolean.kt
Labels: 🎉 feature

#1716 [NEW] Add room_privacy_changed system message handling
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: :+1: improvement

#1728 [FIX] Two factor authentication when using email.
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
Labels: :bug: bug

#1729 [FIX] View less/view more button getting lost
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageAttachmentViewHolder.kt
Labels: :bug: bug

#1738 [IMPROVEMENT] Set members list toolbar title immediately
  app/src/main/java/chat/rocket/android/members/ui/MembersFragment.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: :+1: improvement

#1739 [I18N] Fixed typo on Miembros string for Spanish language
  app/src/main/res/values-es/strings.xml
Labels: :earth_americas: i18n

#1743 [FIX] Mentions were being fetch from favorites instead of the mentions table
  app/src/main/java/chat/rocket/android/db/MessageDao.kt
Labels: :bug: bug

#1745 [FIX] Links not correctly being parsed
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
Labels: :bug: bug

#1750 [FIX] 3.0.0 beta fixes
  app/src/main/java/chat/rocket/android/authentication/signup/ui/SignupFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/db/MessageDao.kt
  app/src/main/java/chat/rocket/android/webview/adminpanel/ui/AdminPanelWebViewFragment.kt
  app/src/main/res/layout/fragment_authentication_login_options.xml
  app/src/main/res/layout/item_actions_attachment.xml
  dependencies.gradle
Labels: :bug: bug

#1751 [FIX] Text being cut off
  app/src/main/res/values/styles.xml
Labels: :art: layout, :bug: bug

#1752 [FIX] admin panel crash
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/webview/adminpanel/di/AdminPanelWebViewFragmentProvider.kt
Labels: :bug: bug

#1759 Update RU strings.xml for better visual perception
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#1758 [I18N] Add missing translations for Hindi
  app/src/main/res/values-hi-rIN/strings.xml
Labels: :earth_americas: i18n

#1764 [UX] Auto scrolling
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  build.gradle
Labels: 🖼 ux

#1771 [FIX] Fixes for Onboarding/Authentication
  app/src/main/java/chat/rocket/android/authentication/loginoptions/presentation/LoginOptionsPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/loginoptions/ui/LoginOptionsFragment.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
  app/src/main/res/layout/fragment_authentication_login_options.xml
  app/src/main/res/values/styles.xml
Labels: :bug: bug

#1778 [IMPROVEMENT] Show last message on chats list with stripped markdown syntax
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomViewHolder.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
Labels: :+1: improvement

#1732 [IMPROVEMENT] Use isVisible Ktx function rather than extension function
  app/src/main/java/chat/rocket/android/authentication/registerusername/ui/RegisterUsernameFragment.kt
  app/src/main/java/chat/rocket/android/authentication/resetpassword/ui/ResetPasswordFragment.kt
  app/src/main/java/chat/rocket/android/chatinformation/ui/MessageInfoFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/PeopleSuggestionsAdapter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/java/chat/rocket/android/util/extensions/Ui.kt
Labels: :truck: chore

#1735 [NEW] Not show last message on search icon click
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomUiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
Labels: 🎉 feature

#1783 [IMPROVEMENT] Dismiss emoji keyboard when starting search
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
Labels: :+1: improvement

#1789 [FIX] Gif files not being animated.
  app/src/main/java/chat/rocket/android/chatroom/ui/Dialog.kt
Labels: :bug: bug

#1770 [NEW] Display user status indicator in members list
  app/src/main/java/chat/rocket/android/members/adapter/MembersAdapter.kt
  app/src/main/java/chat/rocket/android/members/uimodel/MemberUiModel.kt
  app/src/main/res/layout/item_member.xml
Labels: 🎉 feature

#1798 [LAYOUT] Update app icon.
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
Labels: :art: layout

#1801 [CHORE] CircleCi version updates and fixes
  .circleci/config.yml
  app/build-sdk.sh
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  build.gradle
  dependencies.gradle
Labels: :truck: chore

#1753 [NEW] Provides support for http basic authentication
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/server/domain/BasicAuthRepository.kt
  app/src/main/java/chat/rocket/android/server/domain/GetBasicAuthInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SaveBasicAuthInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/model/BasicAuth.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPrefsBasicAuthRepository.kt
  app/src/main/java/chat/rocket/android/util/BasicAuthenticatorInterceptor.kt
Labels: 🎉 feature

#1808 [NEW] Add message action menu item to copy permalink from tapped message
  .circleci/config.yml
  app/build-sdk.sh
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/bottomsheet/MessageActionsBottomSheet.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/ActionsAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/AudioAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/AuthorAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/BaseUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/ColorAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/GenericFileAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/ImageAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/MessageAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/MessageReplyUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/MessageUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UrlPreviewUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/VideoAttachmentUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/suggestion/ChatRoomSuggestionUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/suggestion/CommandSuggestionUiModel.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/suggestion/PeopleSuggestionUiModel.kt
  app/src/main/java/chat/rocket/android/helper/MessageHelper.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  app/src/main/res/drawable/ic_action_message_link_24dp.xml
  app/src/main/res/menu/message_actions.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle
  dependencies.gradle
Labels: 🎉 feature

#1810 [IMPROVEMENT] Image compression
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Dialog.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  util/src/main/java/chat/rocket/android/util/extension/Image.kt
Labels: :+1: improvement
