Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2018-03, with the labels that each got.

#822 [NEW] Improve socket connection
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsView.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManagerFactory.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/RocketChatClientFactory.kt
  app/src/main/java/chat/rocket/android/util/extensions/Animation.kt
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_chat_rooms.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
  dependencies.gradle
Labels: improvement

#828 [IMPROVEMENT] Mark room as read when a new message arrives on the chat room.
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
Labels: improvement

#783 [NEW] Avatar update using URL
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/res/drawable/ic_link_black_24dp.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#787 [NEW] Password Update Feature - Issue #755
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainNavigator.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/settings/di/SettingsFragmentModule.kt
  app/src/main/java/chat/rocket/android/settings/di/SettingsFragmentProvider.kt
  app/src/main/java/chat/rocket/android/settings/password/di/PasswordFragmentModule.kt
  app/src/main/java/chat/rocket/android/settings/password/di/PasswordFragmentProvider.kt
  app/src/main/java/chat/rocket/android/settings/password/presentation/PasswordPresenter.kt
  app/src/main/java/chat/rocket/android/settings/password/presentation/PasswordView.kt
  app/src/main/java/chat/rocket/android/settings/password/ui/PasswordActivity.kt
  app/src/main/java/chat/rocket/android/settings/password/ui/PasswordFragment.kt
  app/src/main/java/chat/rocket/android/settings/presentation/SettingsView.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/layout/app_bar_password.xml
  app/src/main/res/layout/fragment_password.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/menu/navigation.xml
  app/src/main/res/menu/password.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#823 [IMPROVEMENT] Fixed Layout for Login Screen
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
Labels: bug

#843 [FIX] Member details transparency/Pagination
  app/src/main/java/chat/rocket/android/member/ui/MemberBottomSheetFragment.kt
  app/src/main/java/chat/rocket/android/members/di/MembersFragmentModule.kt
  app/src/main/java/chat/rocket/android/members/presentation/MembersNavigator.kt
  app/src/main/java/chat/rocket/android/members/presentation/MembersPresenter.kt
  app/src/main/java/chat/rocket/android/members/ui/MembersFragment.kt
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_member_bottom_sheet.xml
  app/src/main/res/layout/fragment_members.xml
  app/src/main/res/values/colors.xml
Labels: bug, layout

#812 [NEW] feat: Add room-type-symbol(#,@,private) with room-name
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/res/drawable/ic_room_channel.xml
  app/src/main/res/drawable/ic_room_dm.xml
  app/src/main/res/drawable/ic_room_lock.xml
  app/src/main/res/layout/app_bar_chat_room.xml
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/values/dimens.xml
Labels: improvement

#871 [NEW] CAS login support.
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/presentation/AuthenticationNavigator.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerView.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/authentication/signup/ui/SignupFragment.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/ui/TwoFAFragment.kt
  app/src/main/java/chat/rocket/android/helper/AnimationHelper.kt
  app/src/main/java/chat/rocket/android/helper/UrlHelper.kt
  app/src/main/java/chat/rocket/android/members/viewmodel/MemberViewModelMapper.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/server/domain/RefreshSettingsInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SettingsRepository.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesSettingsRepository.kt
  app/src/main/java/chat/rocket/android/util/extensions/Animation.kt
  app/src/main/java/chat/rocket/android/util/extensions/Text.kt
  app/src/main/java/chat/rocket/android/webview/cas/ui/CasWebViewActivity.kt
  app/src/main/java/chat/rocket/android/webview/ui/WebViewActivity.kt
  app/src/main/res/layout/activity_web_view.xml
  app/src/main/res/layout/fragment_authentication_log_in.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#879 [FIX] Behavior of messages with attachments/previews
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: bug

#881 [FIX] Fix emoji parsing on quote markdown
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
Labels: bug

#884 [IMPROVEMENT] Add ripple effect on recyclerview items
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/layout/item_member.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/message_attachment.xml
  app/src/main/res/layout/message_url_preview.xml
  app/src/main/res/values/dimens.xml
Labels: ux

#760 [NEW] Add 'unread messages' marker
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/MessageViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsNavigator.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/res/layout/item_message.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#886 [FIX] Logout
  app/src/main/java/chat/rocket/android/chatrooms/di/ChatRoomsFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatrooms/di/ChatRoomsModule.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsNavigator.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/main/di/MainActivityModule.kt
  app/src/main/java/chat/rocket/android/main/di/MainActivityProvider.kt
  app/src/main/java/chat/rocket/android/main/di/MainModule.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainNavigator.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/profile/di/ProfileFragmentModule.kt
Labels: bug

#888 [NEW] Add capability of adding and clearing reactions to messages
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/adapter/AudioAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/BaseViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ImageAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageReactionsAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/UrlPreviewViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/VideoAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/AudioAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/BaseViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ImageAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/MessageViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ReactionViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/UrlPreviewViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/VideoAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/java/chat/rocket/android/dagger/LocalComponent.kt
  app/src/main/java/chat/rocket/android/dagger/module/LocalModule.kt
  app/src/main/java/chat/rocket/android/widget/emoji/CategoryPagerAdapter.kt
  app/src/main/java/chat/rocket/android/widget/emoji/EmojiKeyboardListener.kt
  app/src/main/java/chat/rocket/android/widget/emoji/EmojiKeyboardPopup.kt
  app/src/main/java/chat/rocket/android/widget/emoji/EmojiListenerAdapter.kt
  app/src/main/java/chat/rocket/android/widget/emoji/EmojiPickerPopup.kt
  app/src/main/java/chat/rocket/android/widget/emoji/EmojiReactionListener.kt
  app/src/main/res/drawable/ic_add_reaction.xml
  app/src/main/res/drawable/rounded_background.xml
  app/src/main/res/layout/emoji_keyboard.xml
  app/src/main/res/layout/emoji_picker.xml
  app/src/main/res/layout/item_add_reaction.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_reaction.xml
  app/src/main/res/layout/layout_reactions.xml
  app/src/main/res/layout/message_attachment.xml
  app/src/main/res/layout/message_url_preview.xml
  app/src/main/res/menu/message_actions.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  dependencies.gradle
Labels: feature

#893 [NEW] Spotlight search if no results found on subscriptions
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainNavigator.kt
  app/src/main/res/layout/message_composer.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#904 [FIX] Sign up screen
  app/src/main/java/chat/rocket/android/authentication/signup/ui/SignupFragment.kt
  app/src/main/res/anim/hold.xml
  app/src/main/res/anim/slide_up.xml
  app/src/main/res/layout/fragment_authentication_log_in.xml
  app/src/main/res/layout/fragment_authentication_sign_up.xml
Labels: bug, layout

#906 [FIX] Rounded avatars
  app/build.gradle
  app/src/main/java/chat/rocket/android/app/utils/ColorImage.kt
  app/src/main/java/chat/rocket/android/app/utils/CustomImageFormatConfigurator.kt
  app/src/main/java/chat/rocket/android/app/utils/SvgDecoder.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/helper/UrlHelper.kt
  app/src/main/java/chat/rocket/android/members/viewmodel/MemberViewModel.kt
  dependencies.gradle
Labels: improvement, layout

#899 [CHORE] Increment version code, name and remove suffix for releases
  app/build.gradle
Labels: release:beta

#918 [NEW] Commands
  app/src/main/java/chat/rocket/android/chatroom/adapter/CommandSuggestionsAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/PeopleSuggestionsAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/RoomSuggestionsAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ChatRoomViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/PeopleViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/suggestion/ChatRoomSuggestionViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/suggestion/CommandSuggestionViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/suggestion/PeopleSuggestionViewModel.kt
  app/src/main/java/chat/rocket/android/widget/autocompletion/strategy/regex/StringMatchingCompletionStrategy.kt
  app/src/main/java/chat/rocket/android/widget/autocompletion/ui/SuggestionsAdapter.kt
  app/src/main/java/chat/rocket/android/widget/autocompletion/ui/SuggestionsView.kt
  app/src/main/res/layout/suggestion_command_item.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#911 [FIX] Keyboard is shown when opening the member list view.
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/members/ui/MembersFragment.kt
  app/src/main/java/chat/rocket/android/util/extensions/Ui.kt
Labels: bug

#929 [CI] Upgrade Circle CI to version 2.0
  .circleci/config.yml
  circle.yml
Labels: ci

#964 [CHORE] Update app dependencies.
  dependencies.gradle
Labels: :truck: chore

#961 [NEW][WIP] Migration of authentications from legacy
  app/build.gradle
  app/src/main/java/chat/rocket/android/app/RocketChatApplication.kt
  app/src/main/java/chat/rocket/android/app/migration/RealmMigration.kt
  app/src/main/java/chat/rocket/android/app/migration/RocketChatLibraryModule.kt
  app/src/main/java/chat/rocket/android/app/migration/RocketChatServerModule.kt
  app/src/main/java/chat/rocket/android/app/migration/model/RealmBasedServerInfo.kt
  app/src/main/java/chat/rocket/android/app/migration/model/RealmEmail.kt
  app/src/main/java/chat/rocket/android/app/migration/model/RealmPreferences.kt
  app/src/main/java/chat/rocket/android/app/migration/model/RealmPublicSetting.kt
  app/src/main/java/chat/rocket/android/app/migration/model/RealmSession.kt
  app/src/main/java/chat/rocket/android/app/migration/model/RealmSettings.kt
  app/src/main/java/chat/rocket/android/app/migration/model/RealmUser.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
  app/src/main/java/chat/rocket/android/infrastructure/LocalRepository.kt
  app/src/main/java/chat/rocket/android/infrastructure/SharedPrefsLocalRepository.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesSettingsRepository.kt
  build.gradle
Labels: 🎉 feature

#969 [NEW] Login with Google (OAuth).
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/helper/UrlHelper.kt
  app/src/main/java/chat/rocket/android/webview/oauth/ui/OauthWebViewActivity.kt
Labels: 🎉 feature

#971 [FIX] Fixed ActionMode always showing on Profile Screen
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
Labels: :bug: bug

#986 [FIX] Issues with OAuth.
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/helper/OauthHelper.kt
  app/src/main/java/chat/rocket/android/helper/UrlHelper.kt
  app/src/main/java/chat/rocket/android/webview/oauth/ui/OauthWebViewActivity.kt
  build.gradle
Labels: :bug: bug

#887 [NEW] feat: Add sorting option for chatrooms
  app/src/main/java/chat/rocket/android/app/RocketChatApplication.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/SimpleSectionedRecyclerViewAdapter.kt
  app/src/main/java/chat/rocket/android/helper/Constants.kt
  app/src/main/java/chat/rocket/android/helper/SharedPreferenceHelper.kt
  app/src/main/res/drawable/ic_sort.xml
  app/src/main/res/layout/chatroom_sort_dialog.xml
  app/src/main/res/layout/item_chatroom_header.xml
  app/src/main/res/menu/chatrooms.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🎉 feature
