Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2018-09, with the labels that each got.

#1649 [FIX] Fixes for FCM registration.
  app/build.gradle
  app/src/foss/java/chat/rocket/android/push/PushToken.kt
  app/src/foss/java/chat/rocket/android/util/GMSManager.kt
  app/src/main/java/chat/rocket/android/app/RocketChatApplication.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt
  app/src/main/java/chat/rocket/android/authentication/signup/presentation/SignupPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/service/MessageService.kt
  app/src/main/java/chat/rocket/android/dagger/AppComponent.kt
  app/src/main/java/chat/rocket/android/dagger/injector/AndroidWorkerInjection.kt
  app/src/main/java/chat/rocket/android/dagger/injector/HasWorkerInjector.kt
  app/src/main/java/chat/rocket/android/dagger/module/AndroidWorkerInjectionModule.kt
  app/src/main/java/chat/rocket/android/dagger/qualifier/WorkerKey.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/util/extensions/RocketChatClient.kt
  app/src/play/AndroidManifest.xml
  app/src/play/java/chat/rocket/android/dagger/module/ServiceBuilder.kt
  app/src/play/java/chat/rocket/android/extensions/GooglePlayServices.kt
  app/src/play/java/chat/rocket/android/push/FirebaseMessagingService.kt
  app/src/play/java/chat/rocket/android/push/FirebaseTokenService.kt
  app/src/play/java/chat/rocket/android/push/PushToken.kt
  app/src/play/java/chat/rocket/android/push/di/FirebaseTokenServiceProvider.kt
  app/src/play/java/chat/rocket/android/push/di/TokenRegistrationSubComponent.kt
  app/src/play/java/chat/rocket/android/push/worker/TokenRegistrationWorker.kt
  app/src/play/java/chat/rocket/android/util/GMSManager.kt
  dependencies.gradle
Labels: :bug: bug

#1650 [FIX] fix multiserver
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesAccountsRepository.kt
Labels: :bug: bug

#1651 [LAYOUT] App icon.
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: :art: layout

#1654 [I18N] Hindi translations
  app/src/main/res/values-hi-rIN/strings.xml
Labels: :earth_americas: i18n

#1652 [I18N] Add Ukrainian language
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: :earth_americas: i18n

#1653 [FIX] Preserves the image aspect ratio
  app/src/main/java/chat/rocket/android/chatroom/ui/Dialog.kt
Labels: :bug: bug

#1655 [LAYOUT] Update round icons
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: :art: layout

#1615 [WIP][FIX] Chat history sync
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/server/domain/MessagesRepository.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/MemoryMessagesRepository.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesMessagesRepository.kt
Labels: :bug: bug

#1659 [FIX] Check file size after compressing the image
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
Labels: :bug: bug

#1661 [FIX] Admin panel crash
  app/src/main/java/chat/rocket/android/webview/adminpanel/ui/AdminPanelWebViewFragment.kt
Labels: :bug: bug

#1663 [I18N] Fix French translation
  app/src/main/res/values-fr/strings.xml
Labels: :earth_americas: i18n

#1667 [I18N] Update french translations
  app/src/main/res/values-fr/strings.xml
Labels: :earth_americas: i18n

#1666 [FIX] Fix random crash emoji keyboard
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiKeyboardPopup.kt
Labels: :bug: bug

#1694 [RELEASE] 2.6.1
  app/build.gradle
  app/src/main/res/values-fr/strings.xml
Labels: :rocket: release:master

#958 [NEW] Save unfinished message
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/helper/KeyboardHelper.kt
  app/src/main/java/chat/rocket/android/infrastructure/LocalRepository.kt
Labels: 🎉 feature

#1690 [NEW] Autocomplete emojis
  app/src/main/java/chat/rocket/android/chatroom/adapter/EmojiSuggestionsAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/suggestion/EmojiSuggestionUiModel.kt
  app/src/main/res/layout/suggestion_emoji_item.xml
  emoji/src/main/java/chat/rocket/android/emoji/EmojiRepository.kt
  suggestions/src/androidTest/java/yampsample/leonardoaramaki/github/com/suggestions/ExampleInstrumentedTest.java
  suggestions/src/main/java/chat/rocket/android/suggestions/model/SuggestionModel.kt
  suggestions/src/main/java/chat/rocket/android/suggestions/strategy/trie/TrieCompletionStrategy.kt
  suggestions/src/main/java/chat/rocket/android/suggestions/strategy/trie/data/Trie.kt
  suggestions/src/main/java/chat/rocket/android/suggestions/strategy/trie/data/TrieNode.kt
  suggestions/src/main/java/chat/rocket/android/suggestions/ui/SuggestionsAdapter.kt
  suggestions/src/main/java/chat/rocket/android/suggestions/ui/SuggestionsView.kt
  suggestions/src/test/java/yampsample/leonardoaramaki/github/com/suggestions/ExampleUnitTest.java
Labels: 🎉 feature

#1695 [NEW] Add collapsable feature to quotes
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageReplyViewHolder.kt
  app/src/main/res/layout/item_message_attachment.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1697 [FIX] Fix markdown parsing for mentions, emphasis and strong emphasis
  app/src/main/java/chat/rocket/android/chatroom/ui/StrikethroughDelimiterProcessor.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  dependencies.gradle
Labels: :bug: bug
