Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2018-08, with the labels that each got.

#1560 [BUG] Fixed black colour not selected
  draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
Labels: :bug: bug

#1571 [CHORE] Update dependencies
  app/build.gradle
  app/gradle/wrapper/gradle-wrapper.properties
  build.gradle
  dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
  wear/build.gradle
Labels: :truck: chore

#1562 [NEW] Key icon
  app/src/main/res/drawable/ic_key_20dp.xml
Labels: :art: layout

#1527 [NEW] Upload/reset avatar.
  app/src/main/java/chat/rocket/android/db/DatabaseManager.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfileView.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/res/drawable/ic_image_black_24dp.xml
  app/src/main/res/drawable/ic_link_black_24dp.xml
  app/src/main/res/drawable/ic_photo_camera_black_24dp.xml
  app/src/main/res/layout/fragment_member_bottom_sheet.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/update_avatar_options.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  util/src/main/java/chat/rocket/android/util/extension/Image.kt
Labels: 🎉 feature

#1593 [IMPROVEMENT] immediately try to reconnect when coming from the Background.
  app/src/main/java/chat/rocket/android/app/AppLifecycleObserver.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
Labels: :+1: improvement

#1570 [NEW] Adds the admin panel.
  app/src/main/java/chat/rocket/android/createchannel/ui/CreateChannelFragment.kt
  app/src/main/java/chat/rocket/android/helper/UserHelper.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainNavigator.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/main/ui/Menu.kt
  app/src/main/java/chat/rocket/android/server/domain/PermissionsInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/PermissionsRepository.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/java/chat/rocket/android/util/extensions/String.kt
  app/src/main/java/chat/rocket/android/webview/adminpanel/ui/AdminPanelWebViewFragment.kt
  app/src/main/res/drawable/ic_logout_black_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_admin_panel_web_view.xml
  app/src/main/res/menu/navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1582 [NEW] Permission list
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/server/domain/PermissionsRepository.kt
  app/src/main/java/chat/rocket/android/server/domain/RefreshPermissionsInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/RefreshSettingsInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SaveSettingsInteractor.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesPermissionsRepository.kt
  build.gradle
Labels: 🎉 feature

#1596 [FIX] File size validation
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
Labels: :bug: bug

#1611 [FIX] Temporary workaround for HandlerContext error.
  app/src/main/java/chat/rocket/android/authentication/ui/AuthenticationActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
  app/src/main/java/chat/rocket/android/push/DirectReplyReceiver.kt
  app/src/main/java/chat/rocket/android/util/extensions/Fragment.kt
  app/src/main/java/chat/rocket/android/util/livedata/TransformedLiveData.kt
  emoji/build.gradle
  emoji/src/main/java/chat/rocket/android/emoji/internal/EmojiPagerAdapter.kt
  util/src/main/java/chat/rocket/android/util/extension/Coroutines.kt
  util/src/main/java/chat/rocket/android/util/temp/HandlerContext.kt
Labels: :bug: bug

#1614 [FIX] Building error
  app/src/androidTest/java/chat/rocket/android/chatroom/ui/ChatRoomFragmentTest.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  build.gradle
Labels: :bug: bug

#1567 [NEW] Emoji custom support
  app/build.gradle
  app/src/main/java/chat/rocket/android/app/RocketChatApplication.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/util/extensions/Text.kt
  app/src/main/res/values/dimens.xml
  dependencies.gradle
  emoji/build.gradle
  emoji/proguard-rules.pro
  emoji/src/main/java/chat/rocket/android/emoji/ComposerEditText.kt
  emoji/src/main/java/chat/rocket/android/emoji/Emoji.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiDao.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiKeyboardPopup.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiParser.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiPickerPopup.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiRepository.kt
  emoji/src/main/java/chat/rocket/android/emoji/internal/EmojiCategory.kt
  emoji/src/main/java/chat/rocket/android/emoji/internal/EmojiGlideModule.kt
  emoji/src/main/java/chat/rocket/android/emoji/internal/EmojiPagerAdapter.kt
  emoji/src/main/java/chat/rocket/android/emoji/internal/Extensions.kt
  emoji/src/main/java/chat/rocket/android/emoji/internal/db/EmojiDatabase.kt
  emoji/src/main/java/chat/rocket/android/emoji/internal/db/StringListConverter.kt
  emoji/src/main/res/drawable-hdpi/ic_emoji_custom.png
  emoji/src/main/res/drawable-mdpi/ic_emoji_custom.png
  emoji/src/main/res/drawable-xhdpi/ic_emoji_custom.png
  emoji/src/main/res/drawable-xxhdpi/ic_emoji_custom.png
  emoji/src/main/res/drawable-xxxhdpi/ic_emoji_custom.png
  emoji/src/main/res/layout/emoji_image_row_item.xml
  emoji/src/main/res/layout/emoji_row_item.xml
  emoji/src/main/res/values/dimens.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: 🎉 feature

#1618 [NEW] Add the support for the Google Analytics For Firebase
  app/src/foss/java/chat/rocket/android/analytics/AnswersAnalytics.kt
  app/src/foss/java/chat/rocket/android/analytics/GoogleAnalyticsForFirebase.kt
  app/src/main/java/chat/rocket/android/about/ui/AboutFragment.kt
  app/src/main/java/chat/rocket/android/analytics/Analytics.kt
  app/src/main/java/chat/rocket/android/analytics/AnalyticsManager.kt
  app/src/main/java/chat/rocket/android/analytics/event/AuthenticationEvent.kt
  app/src/main/java/chat/rocket/android/analytics/event/ScreenViewEvent.kt
  app/src/main/java/chat/rocket/android/analytics/event/SubscriptionTypeEvent.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/ui/RegisterUsernameFragment.kt
  app/src/main/java/chat/rocket/android/authentication/resetpassword/ui/ResetPasswordFragment.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/authentication/signup/presentation/SignupPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/signup/ui/SignupFragment.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/ui/TwoFAFragment.kt
  app/src/main/java/chat/rocket/android/chatinformation/ui/MessageInfoFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/createchannel/ui/CreateChannelFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/favoritemessages/ui/FavoriteMessagesFragment.kt
  app/src/main/java/chat/rocket/android/files/ui/FilesFragment.kt
  app/src/main/java/chat/rocket/android/members/ui/MemberBottomSheetFragment.kt
  app/src/main/java/chat/rocket/android/members/ui/MembersFragment.kt
  app/src/main/java/chat/rocket/android/mentions/ui/MentionsFragment.kt
  app/src/main/java/chat/rocket/android/pinnedmessages/ui/PinnedMessagesFragment.kt
  app/src/main/java/chat/rocket/android/preferences/ui/PreferencesFragment.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/server/domain/AccountsRepository.kt
  app/src/main/java/chat/rocket/android/server/domain/GetAccountsInteractor.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesAccountsRepository.kt
  app/src/main/java/chat/rocket/android/server/presentation/ChangeServerPresenter.kt
  app/src/main/java/chat/rocket/android/settings/password/ui/PasswordFragment.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/play/java/chat/rocket/android/analytics/AnswersAnalytics.kt
  app/src/play/java/chat/rocket/android/analytics/GoogleAnalyticsForFirebase.kt
  dependencies.gradle
  util/build.gradle
Labels: 🎉 feature

#1633 [FIX] Analytics manager not initialized
  app/src/main/java/chat/rocket/android/about/di/AboutFragmentProvider.kt
  app/src/main/java/chat/rocket/android/about/ui/AboutFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/members/di/MembersFragmentProvider.kt
  app/src/main/java/chat/rocket/android/members/ui/MemberBottomSheetFragment.kt
  emoji/schemas/chat.rocket.android.emoji.internal.db.EmojiDatabase/1.json
Labels: :bug: bug

#1635 [FIX] Create channel fragment
  app/src/main/java/chat/rocket/android/files/uimodel/FileUiModel.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesAccountsRepository.kt
  app/src/main/java/chat/rocket/android/settings/password/presentation/PasswordPresenter.kt
  app/src/main/res/values-ja/strings.xml
  dependencies.gradle
Labels: :bug: bug

#1639 [FIX] Out of memory when sending large image
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Dialog.kt
  app/src/main/java/chat/rocket/android/util/extensions/Uri.kt
Labels: :bug: bug

#1641 [I18N] Russian translation
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#1642 [LAYOUT] App icon
  app/src/main/ic_launcher-web.png
  app/src/main/res/drawable/ic_launcher_foreground.xml
Labels: :art: layout
