Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2018-05, with the labels that each got.

#1169 [NEW] Edited message indicator
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageViewHolder.kt
  app/src/main/res/layout/item_message.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1237 [CHORE] Merge beta into develop
  .circleci/config.yml
  app/build.gradle
  app/src/androidTest/java/chat/rocket/android/chatroom/ui/ChatRoomFragmentTest.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/AudioAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/AuthorAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/BaseViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ColorAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/GenericFileAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ImageAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/VideoAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/server/domain/RefreshSettingsInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SettingsRepository.kt
  app/src/main/java/chat/rocket/android/util/extensions/Collections.kt
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_message_attachment.xml
  app/src/test/java/chat/rocket/android/server/domain/SettingsRepositoryTest.kt
  app/src/test/java/chat/rocket/android/server/domain/SettingsRepositoryUploadMimeFilterProperlyParsesWhitelistTest.kt
  dependencies.gradle
Labels: :truck: chore

#1239 [FIX] Fix url preview on messages
  app/src/main/java/chat/rocket/android/chatroom/adapter/UrlPreviewViewHolder.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  app/src/main/java/chat/rocket/android/util/extensions/View.kt
Labels: :bug: bug

#1240 [DO NOT MERGE][RELEASE] Merge beta into develop
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/adapter/UrlPreviewViewHolder.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  app/src/main/java/chat/rocket/android/util/extensions/View.kt
Labels: :rocket: release:beta

#1241 [RELEASE] Merge beta into master
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/adapter/UrlPreviewViewHolder.kt
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
  app/src/main/java/chat/rocket/android/util/extensions/View.kt
Labels: :rocket: release:master

#1213 [IMPROVEMENT] Remove the FrescoAuthInterceptor
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/dagger/qualifier/ForFresco.kt
  app/src/main/java/chat/rocket/android/helper/FrescoAuthInterceptor.kt
Labels: :+1: improvement

#1252 [NEW] Add mute and unmute system messages
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: :+1: improvement

#1238 [NEW] Send typing status feature.
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/main/viewmodel/NavHeaderViewModel.kt
  app/src/main/java/chat/rocket/android/util/extensions/Rx.kt
Labels: 🎉 feature

#1255 [i18n] Ukrainian translation file.
  app/src/main/res/values-uk-rUA/strings.xml
Labels: :earth_americas: i18n

#1258 [NEW] Detect redirect on server info
  app/build.gradle
  app/src/main/java/chat/rocket/android/authentication/server/presentation/VersionCheckView.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
Labels: :bug: bug, 🎉 feature

#1259 [RELEASE] Merge beta into master
  app/build.gradle
  app/src/main/java/chat/rocket/android/authentication/server/presentation/VersionCheckView.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
Labels: :rocket: release:master

#1260 [RELEAE] Merge beta into develop
  app/src/main/java/chat/rocket/android/authentication/server/presentation/VersionCheckView.kt
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
Labels: :rocket: release:beta

#1257 [NEW] Show subscription role change system messages
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: :+1: improvement

#1290 [IMPROVEMENT] Update gradle-wrapper.properties by adding SHA-256 comparasion
  gradle/wrapper/gradle-wrapper.properties
Labels: :+1: improvement

#1309 [IMPROVEMENT] Shows only the chat icon on the chat room view.
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/java/chat/rocket/android/favoritemessages/ui/FavoriteMessagesFragment.kt
  app/src/main/java/chat/rocket/android/files/ui/FilesFragment.kt
  app/src/main/java/chat/rocket/android/members/ui/MembersFragment.kt
  app/src/main/java/chat/rocket/android/pinnedmessages/ui/PinnedMessagesFragment.kt
  app/src/main/res/drawable/ic_hashtag_12dp.xml
  app/src/main/res/drawable/ic_hashtag_black_12dp.xml
  app/src/main/res/drawable/ic_lock_12_dp.xml
  app/src/main/res/drawable/ic_lock_black_12_dp.xml
  app/src/main/res/drawable/ic_room_channel.xml
  app/src/main/res/drawable/ic_room_dm.xml
  app/src/main/res/drawable/ic_room_lock.xml
  app/src/main/res/layout/app_bar_chat_room.xml
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/values/dimens.xml
Labels: :+1: improvement

#1318 [FIX] Download button.
  app/src/main/java/chat/rocket/android/chatroom/adapter/ImageAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/files/ui/FilesFragment.kt
  app/src/main/java/chat/rocket/android/helper/ImageHelper.kt
  app/src/main/res/layout/fragment_files.xml
Labels: :bug: bug

#1320 [FIX] Composer buttons vanishing in thin air
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#1322 [NEW] Hop to chat room when tapping on notification
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainNavigator.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/push/PushManager.kt
  app/src/main/java/chat/rocket/android/server/presentation/ChangeServerNavigator.kt
  app/src/main/java/chat/rocket/android/server/presentation/ChangeServerPresenter.kt
  app/src/main/java/chat/rocket/android/server/ui/ChangeServerActivity.kt
Labels: :+1: improvement

#1321 [FIX] Open DM showing Join Chat button
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
Labels: :bug: bug
