Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2018-06, with the labels that each got.

#1326 [NEW] SAML support
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/util/extensions/String.kt
  app/src/main/java/chat/rocket/android/webview/oauth/ui/OauthWebViewActivity.kt
  app/src/main/java/chat/rocket/android/webview/sso/ui/SsoWebViewActivity.kt
Labels: 🎉 feature

#1332 [FIX] File list
  app/src/main/java/chat/rocket/android/files/viewmodel/FileViewModel.kt
Labels: :bug: bug

#1330 [FIX] Check if fragment already has a view and is still attached
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#1329 [I18N] Russian translation file
  app/src/main/res/values-uk-rRU/strings.xml
Labels: :earth_americas: i18n

#1334 [IMPROVEMENT] Google Smart Lock feature refactor
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginView.kt
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/signup/presentation/SignupPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/signup/presentation/SignupView.kt
  app/src/main/java/chat/rocket/android/authentication/signup/ui/SignupFragment.kt
  app/src/main/java/chat/rocket/android/helper/SmartLockHelper.kt
  app/src/main/res/layout/fragment_authentication_log_in.xml
Labels: :+1: improvement, 🖼 ux

#1336 [IMPROVEMENT] Show toast on copy message
  app/src/main/java/chat/rocket/android/app/DateTimeHelper.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-uk-rRU/strings.xml
  app/src/main/res/values/strings.xml
Labels: :+1: improvement

#1340 [CHORE] Update recommended server version.
  app/build.gradle
Labels: :truck: chore

#1337 [BUG] SaveInstanceState on orientation change
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
Labels: :bug: bug

#1345 [FIX] 2.3.0 hotfix1
  app/build.gradle
  app/src/main/java/chat/rocket/android/authentication/di/AuthenticationModule.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt
  app/src/main/java/chat/rocket/android/authentication/resetpassword/presentation/ResetPasswordPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/signup/presentation/SignupPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/ui/AuthenticationActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/di/ChatRoomFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatroom/di/ChatRoomFragmentProvider.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/di/ChatRoomsFragmentProvider.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/dagger/qualifier/ForAuthentication.kt
  app/src/main/java/chat/rocket/android/favoritemessages/di/FavoriteMessagesFragmentProvider.kt
  app/src/main/java/chat/rocket/android/pinnedmessages/di/PinnedMessagesFragmentProvider.kt
  app/src/main/java/chat/rocket/android/server/domain/GetConnectingServerInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SaveConnectingServerInteractor.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPrefsConnectingServerRepository.kt
  app/src/main/java/chat/rocket/android/util/HttpLoggingInterceptor.kt
  app/src/main/java/chat/rocket/android/util/extensions/Ui.kt
  app/src/main/java/chat/rocket/android/util/extensions/View.kt
Labels: :bug: bug

#1351 [RELEASE] 2.3.2 - HOTFIX
  app/build.gradle
  app/src/main/java/chat/rocket/android/app/RocketChatApplication.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/infrastructure/CrashlyticsWrapper.kt
  app/src/main/java/chat/rocket/android/server/domain/SettingsRepository.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesSettingsRepository.kt
Labels: :bug: bug

#1344 [IMPROVEMENT] Removes web view cookies for OAuth and SSO.
  app/src/main/java/chat/rocket/android/webview/oauth/ui/OauthWebViewActivity.kt
  app/src/main/java/chat/rocket/android/webview/sso/ui/SsoWebViewActivity.kt
Labels: :+1: improvement

#1359 [IMPROVEMENT] Improvement in Hindi translations
  app/src/main/res/values-hi-rIN/strings.xml
Labels: :earth_americas: i18n

#1338 [NEW] Add read receipt support
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/chatinformation/adapter/ReadReceiptAdapter.kt
  app/src/main/java/chat/rocket/android/chatinformation/di/MessageInfoFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatinformation/di/MessageInfoFragmentProvider.kt
  app/src/main/java/chat/rocket/android/chatinformation/presentation/MessageInfoPresenter.kt
  app/src/main/java/chat/rocket/android/chatinformation/presentation/MessageInfoView.kt
  app/src/main/java/chat/rocket/android/chatinformation/ui/MessageInfoActivity.kt
  app/src/main/java/chat/rocket/android/chatinformation/ui/MessageInfoFragment.kt
  app/src/main/java/chat/rocket/android/chatinformation/viewmodel/ReadReceiptViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/BaseViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/AudioAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/AuthorAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/BaseViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ColorAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/GenericFileAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ImageAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/MessageAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/MessageReplyViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/MessageViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/UrlPreviewViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/VideoAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/helper/UserHelper.kt
  app/src/main/java/chat/rocket/android/server/domain/RefreshSettingsInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SettingsRepository.kt
  app/src/main/res/drawable/ic_action_message_info_outline_24dp.xml
  app/src/main/res/drawable/ic_check_read_24dp.xml
  app/src/main/res/drawable/ic_check_unread_24dp.xml
  app/src/main/res/layout/fragment_message_info.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_read_receipt.xml
  app/src/main/res/menu/message_actions.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1364 [RELEASE] Merge beta into master
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/chatinformation/adapter/ReadReceiptAdapter.kt
  app/src/main/java/chat/rocket/android/chatinformation/di/MessageInfoFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatinformation/di/MessageInfoFragmentProvider.kt
  app/src/main/java/chat/rocket/android/chatinformation/presentation/MessageInfoPresenter.kt
  app/src/main/java/chat/rocket/android/chatinformation/presentation/MessageInfoView.kt
  app/src/main/java/chat/rocket/android/chatinformation/ui/MessageInfoActivity.kt
  app/src/main/java/chat/rocket/android/chatinformation/ui/MessageInfoFragment.kt
  app/src/main/java/chat/rocket/android/chatinformation/viewmodel/ReadReceiptViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/BaseViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/MessageViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/AudioAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/AuthorAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/BaseViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ColorAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/GenericFileAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ImageAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/MessageAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/MessageReplyViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/MessageViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/UrlPreviewViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/VideoAttachmentViewModel.kt
  app/src/main/java/chat/rocket/android/chatroom/viewmodel/ViewModelMapper.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/helper/UserHelper.kt
  app/src/main/java/chat/rocket/android/server/domain/RefreshSettingsInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SettingsRepository.kt
  app/src/main/res/drawable/ic_action_message_info_outline_24dp.xml
  app/src/main/res/drawable/ic_check_read_24dp.xml
  app/src/main/res/drawable/ic_check_unread_24dp.xml
  app/src/main/res/layout/fragment_message_info.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_read_receipt.xml
  app/src/main/res/menu/message_actions.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
  dependencies.gradle
Labels: :rocket: release:master

#1388 [BUG] Fixed bottom row of emojis
  app/src/main/res/layout/emoji_keyboard.xml
Labels: :bug: bug

#1391 [FIX] Chat list scrolls down when a new message arrives in a channel.
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#1384 [NEW] Compress image
  app/src/main/java/chat/rocket/android/chatroom/domain/UriInteractor.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/util/extensions/Animation.kt
  app/src/main/java/chat/rocket/android/util/extensions/Image.kt
  app/src/main/java/chat/rocket/android/util/extensions/Ui.kt
  app/src/main/java/chat/rocket/android/util/extensions/Uri.kt
Labels: :+1: improvement

#1389 [CHORE] Update instruction on how to build this project.
  README.md
Labels: :truck: chore

#1404 [IMPROVEMENT] Improvements in Russian translation
  app/src/main/res/values-uk-rRU/strings.xml
Labels: :earth_americas: i18n

#1396 [NEW] Mention list
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/files/presentation/FilesView.kt
  app/src/main/java/chat/rocket/android/mentions/di/MentionsFragmentModule.kt
  app/src/main/java/chat/rocket/android/mentions/di/MentionsFragmentProvider.kt
  app/src/main/java/chat/rocket/android/mentions/presentention/MentionsPresenter.kt
  app/src/main/java/chat/rocket/android/mentions/presentention/MentionsView.kt
  app/src/main/java/chat/rocket/android/mentions/ui/MentionsFragment.kt
  app/src/main/java/chat/rocket/android/pinnedmessages/di/PinnedMessagesFragmentModule.kt
  app/src/main/java/chat/rocket/android/pinnedmessages/di/PinnedMessagesFragmentProvider.kt
  app/src/main/res/layout/fragment_mentions.xml
  app/src/main/res/menu/chatroom_actions.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-uk-rRU/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1405 [IMPROVEMENT] Quote bar redesign and set it to open even if offline
  app/src/main/java/chat/rocket/android/chatroom/adapter/ColorAttachmentViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ActionSnackbar.kt
  app/src/main/res/drawable/ic_close_gray_24dp.xml
  app/src/main/res/drawable/quote_vertical_blue_bar.xml
  app/src/main/res/drawable/quote_vertical_gray_bar.xml
  app/src/main/res/layout/item_author_attachment.xml
  app/src/main/res/layout/item_color_attachment.xml
  app/src/main/res/layout/item_message_attachment.xml
  app/src/main/res/layout/message_action_bar.xml
  app/src/main/res/layout/message_list.xml
  app/src/main/res/layout/suggestion_command_item.xml
  app/src/main/res/layout/suggestion_member_item.xml
  app/src/main/res/layout/suggestion_room_item.xml
Labels: :+1: improvement

#1410 [NEW] Favorite/Unfavorite chatroom
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomView.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainNavigator.kt
  app/src/main/res/drawable/ic_star_border_white_24dp.xml
  app/src/main/res/drawable/ic_star_yellow_24dp.xml
  app/src/main/res/menu/chatroom_actions.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-uk-rRU/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#1413 [NEW] Set user agent
  app/src/main/java/chat/rocket/android/server/infraestructure/RocketChatClientFactory.kt
Labels: :+1: improvement

#1414 [NEW] Allow room names whit special chars
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomUiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsAdapter.kt
  app/src/main/java/chat/rocket/android/helper/MessageHelper.kt
  app/src/main/java/chat/rocket/android/server/domain/SettingsRepository.kt
Labels: :+1: improvement

#1420 [IMPROVEMENT] Uses framework's Bottomsheet
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/adapter/BaseViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/bottomsheet/BottomSheetMenu.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/bottomsheet/MessageActionsBottomSheet.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/bottomsheet/adapter/ActionListAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/bottomsheet/adapter/ListBottomSheetAdapter.kt
  app/src/main/java/chat/rocket/android/util/extensions/Ui.kt
  app/src/main/res/layout/message_action_item.xml
  app/src/main/res/layout/message_bottomsheet.xml
  app/src/main/res/menu/message_actions.xml
  build.gradle
  dependencies.gradle
Labels: :+1: improvement

#1422 [FIX] Member, Pinned, Favorite and File list not showing bug.
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/favoritemessages/di/FavoriteMessagesFragmentModule.kt
  app/src/main/java/chat/rocket/android/favoritemessages/di/FavoriteMessagesFragmentProvider.kt
  app/src/main/java/chat/rocket/android/favoritemessages/presentation/FavoriteMessagesPresenter.kt
  app/src/main/java/chat/rocket/android/files/di/FilesFragmentModule.kt
  app/src/main/java/chat/rocket/android/files/presentation/FilesPresenter.kt
  app/src/main/java/chat/rocket/android/members/di/MembersFragmentModule.kt
  app/src/main/java/chat/rocket/android/members/presentation/MembersPresenter.kt
  app/src/main/java/chat/rocket/android/pinnedmessages/di/PinnedMessagesFragmentModule.kt
  app/src/main/java/chat/rocket/android/pinnedmessages/presentation/PinnedMessagesPresenter.kt
Labels: :bug: bug
