Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2019-07, with the labels that each got.

#2392 [I18n] Add missing translation in german strings.xml
  app/src/main/res/values-de/strings.xml
Labels: :earth_americas: i18n

#2396 [FIX][IMPROVEMENT] Fixes connectivity issues and improves the app speed up at the start
  app/src/main/java/chat/rocket/android/app/AppLifecycleObserver.kt
  app/src/main/java/chat/rocket/android/authentication/onboarding/presentation/OnBoardingPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/server/presentation/ServerPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/di/ChatRoomFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/di/ChatRoomsFragmentModule.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/directory/presentation/DirectoryPresenter.kt
  app/src/main/java/chat/rocket/android/directory/uimodel/DirectoryUiModelMapper.kt
  app/src/main/java/chat/rocket/android/favoritemessages/presentation/FavoriteMessagesPresenter.kt
  app/src/main/java/chat/rocket/android/files/presentation/FilesPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/members/presentation/MembersPresenter.kt
  app/src/main/java/chat/rocket/android/members/uimodel/MemberUiModelMapper.kt
  app/src/main/java/chat/rocket/android/mentions/presentention/MentionsPresenter.kt
  app/src/main/java/chat/rocket/android/pinnedmessages/presentation/PinnedMessagesPresenter.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/server/domain/GetCurrentServerInteractor.kt
  app/src/main/java/chat/rocket/android/server/infrastructure/ConnectionManager.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
  app/src/main/java/chat/rocket/android/servers/presentation/ServersPresenter.kt
  app/src/main/java/chat/rocket/android/settings/presentation/SettingsPresenter.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/java/chat/rocket/android/sortingandgrouping/presentation/SortingAndGroupingPresenter.kt
  app/src/main/res/layout/fragment_chat_rooms.xml
  app/src/main/res/values/strings.xml
  build.gradle
  dependencies.gradle
  util/src/main/java/chat/rocket/android/util/extension/Number.kt
Labels: :+1: improvement, :bug: bug

#2397 [FIX] Fixes app exceptions
  app/src/main/java/chat/rocket/android/app/AppLifecycleObserver.kt
  app/src/main/java/chat/rocket/android/chatdetails/presentation/ChatDetailsPresenter.kt
  app/src/main/java/chat/rocket/android/chatinformation/presentation/MessageInfoPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/service/MessageService.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/db/DatabaseManagerFactory.kt
  app/src/main/java/chat/rocket/android/directory/ui/DirectoryFragment.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/push/DirectReplyReceiver.kt
  app/src/main/java/chat/rocket/android/server/infrastructure/ConnectionManagerFactory.kt
  app/src/main/java/chat/rocket/android/server/infrastructure/DatabaseMessageMapper.kt
  app/src/main/java/chat/rocket/android/settings/presentation/SettingsPresenter.kt
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsPresenter.kt
  app/src/main/java/chat/rocket/android/userdetails/ui/UserDetailsFragment.kt
  app/src/main/java/chat/rocket/android/videoconference/presenter/VideoConferencePresenter.kt
Labels: :bug: bug

#2351 [NEW] Manage Users in a Room(Add/Remove)
  app/src/main/java/chat/rocket/android/analytics/event/ScreenViewEvent.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/createchannel/ui/CreateChannelFragment.kt
  app/src/main/java/chat/rocket/android/dagger/module/ActivityBuilder.kt
  app/src/main/java/chat/rocket/android/helper/ChatRoomRoleHelper.kt
  app/src/main/java/chat/rocket/android/inviteusers/di/InviteUsersFragmentModule.kt
  app/src/main/java/chat/rocket/android/inviteusers/di/InviteUsersFragmentProvider.kt
  app/src/main/java/chat/rocket/android/inviteusers/presentation/InviteUsersPresenter.kt
  app/src/main/java/chat/rocket/android/inviteusers/presentation/InviteUsersView.kt
  app/src/main/java/chat/rocket/android/inviteusers/ui/InviteUsersFragment.kt
  app/src/main/java/chat/rocket/android/members/presentation/MembersPresenter.kt
  app/src/main/java/chat/rocket/android/members/presentation/MembersView.kt
  app/src/main/java/chat/rocket/android/members/ui/MembersFragment.kt
  app/src/main/java/chat/rocket/android/server/domain/PermissionsInteractor.kt
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsPresenter.kt
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsView.kt
  app/src/main/java/chat/rocket/android/userdetails/ui/UserDetailsFragment.kt
  app/src/main/res/drawable/ic_add_white_24dp.xml
  app/src/main/res/drawable/ic_leave.xml
  app/src/main/res/layout/fragment_invite_users.xml
  app/src/main/res/layout/fragment_members.xml
  app/src/main/res/layout/fragment_user_details.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#2399 [FIX] Unable to delete own account
  app/src/main/java/chat/rocket/android/settings/presentation/SettingsPresenter.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/res/layout/dialog_delete_account.xml
  util/src/main/java/chat/rocket/android/util/extension/Text.kt
Labels: :bug: bug

#2403 [FIX] Illegal state exception issue.
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
Labels: :bug: bug

#2412 [FIX] Message not being sent for new chats.
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
Labels: :bug: bug

#2404 [FIX] Null pointer exception.
  app/src/main/java/chat/rocket/android/chatdetails/viewmodel/ChatDetailsViewModel.kt
Labels: :bug: bug

#2413 [FIX] Update jitsi library version.
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
  app/src/main/java/chat/rocket/android/helper/JitsiHelper.kt
  app/src/main/java/chat/rocket/android/videoconference/presenter/JitsiVideoConferenceView.kt
  app/src/main/java/chat/rocket/android/videoconference/presenter/VideoConferencePresenter.kt
  app/src/main/java/chat/rocket/android/videoconference/ui/VideoConferenceActivity.kt
  dependencies.gradle
Labels: :bug: bug

#2415 [FIX] Rooms not showing real time messages.
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/server/infrastructure/ConnectionManager.kt
Labels: :bug: bug
