Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2019-03, with the labels that each got.

#2096 [FIX] Disable send button while sending message
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
Labels: :bug: bug

#2095 [FIX] Clear notifications after opening the app
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
Labels: :+1: improvement

#2001 [FIX] Fix new direct chat message bug
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
Labels: :bug: bug

#2035 [FIX] Edit your profile and your password is reset
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
Labels: :bug: bug

#2020 [I18n] Fix typo in Russian language file
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#2048 [FIX] Avatar cache bug
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
Labels: :bug: bug

#2054 [FIX] Null username being shown while sending messages without internet
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
Labels: :bug: bug

#2039 [FIX] Show only email apps for sending email
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
Labels: :bug: bug

#2105 [FIX] App bar title changes when rotating the screen.
  app/src/main/java/chat/rocket/android/preferences/ui/PreferencesFragment.kt
Labels: :bug: bug

#2092 [FIX] About fragment app bar title is change from "About" to "Rocket.Chat" on rotate.
  app/src/main/java/chat/rocket/android/about/ui/AboutFragment.kt
Labels: :bug: bug

#2089 [FIX] Chatroom showing empty messages in RTL layout
  app/src/main/res/layout/item_message.xml
Labels: :bug: bug

#2075 [FIX] Added default background image for avatar image view
  app/src/main/res/drawable/bg_empty_user_avatar.xml
  app/src/main/res/layout/avatar_profile.xml
  app/src/main/res/layout/nav_header.xml
Labels: :bug: bug

#2051 [FIX] Fixes app crashes when channel Details button is clicked while scrolling
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#2053 [FIX] Mistakes on the README.md.
  README.md
Labels: :memo: docs

#1961 [NEW] Add erase feature in drawing
  draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
  draw/src/main/java/chat/rocket/android/draw/widget/CustomDrawView.kt
Labels: 🎉 feature

#2057 [FIX] Saving unsend message
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
Labels: :bug: bug

#2097 [IMPROVEMENT] Delete account dialog UI
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/res/layout/item_account_delete.xml
Labels: :+1: improvement, :art: layout

#1959 [NEW] Group chats by favorites
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomUiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/model/RoomUiModel.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#2111 [IMPROVEMENT] Changing search field width should be the max width
  app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
Labels: :+1: improvement, 🖼 ux

#2013 [REFACTOR] Coroutines yield
  app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
  app/src/main/java/chat/rocket/android/util/IO.kt
Labels: :wrench: refactor

#2121 [FIX][CI] Revert "[REFACTOR] Coroutines yield"
  app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
  app/src/main/java/chat/rocket/android/util/IO.kt
Labels: 👷ci

#2093 [REFACTOR] Handle nullable on arguments extra
  app/src/main/java/chat/rocket/android/authentication/login/ui/LoginFragment.kt
  app/src/main/java/chat/rocket/android/authentication/loginoptions/ui/LoginOptionsFragment.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/ui/RegisterUsernameFragment.kt
  app/src/main/java/chat/rocket/android/authentication/signup/ui/SignupFragment.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/ui/TwoFAFragment.kt
  app/src/main/java/chat/rocket/android/chatdetails/ui/ChatDetailsFragment.kt
  app/src/main/java/chat/rocket/android/chatinformation/ui/MessageInfoFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ActionsListAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/RoomSuggestionsAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/UrlPreviewViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Dialog.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomViewHolder.kt
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomsAdapter.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/createchannel/ui/CreateChannelFragment.kt
  app/src/main/java/chat/rocket/android/db/DatabaseManager.kt
  app/src/main/java/chat/rocket/android/db/model/Attachments.kt
  app/src/main/java/chat/rocket/android/favoritemessages/ui/FavoriteMessagesFragment.kt
  app/src/main/java/chat/rocket/android/files/ui/FilesFragment.kt
  app/src/main/java/chat/rocket/android/helper/ImageHelper.kt
  app/src/main/java/chat/rocket/android/members/adapter/MembersAdapter.kt
  app/src/main/java/chat/rocket/android/members/ui/MembersFragment.kt
  app/src/main/java/chat/rocket/android/mentions/ui/MentionsFragment.kt
  app/src/main/java/chat/rocket/android/pinnedmessages/ui/PinnedMessagesFragment.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/push/PushManager.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/ConnectionManager.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/DatabaseMessageMapper.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/DatabaseMessagesRepository.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesAccountsRepository.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPrefsBasicAuthRepository.kt
  app/src/main/java/chat/rocket/android/server/presentation/ChangeServerPresenter.kt
  app/src/main/java/chat/rocket/android/userdetails/ui/UserDetailsFragment.kt
  app/src/main/java/chat/rocket/android/util/HttpLoggingInterceptor.kt
  app/src/main/java/chat/rocket/android/util/extensions/String.kt
  app/src/main/java/chat/rocket/android/webview/adminpanel/ui/AdminPanelWebViewFragment.kt
  app/src/main/java/chat/rocket/android/widget/DividerItemDecoration.kt
  util/src/main/java/chat/rocket/android/util/extension/Widget.kt
Labels: :wrench: refactor

#2124 [IMPROVEMENT] Save the scroll Position of chatRoomsFragment
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
Labels: :+1: improvement

#2127 [I18N] Portuguese (Portugal)
  app/src/main/res/values-pt-rPT/strings.xml
Labels: :earth_americas: i18n

#2069 [FIX] About Screen in landscape view
  app/src/main/res/layout/fragment_about.xml
Labels: :+1: improvement, 🖼 ux

#2129 [I18N] Add French and Some Hindi Translations
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
Labels: :earth_americas: i18n

#2110 [IMPROVEMENT] Chat list UI improvements
  app/src/main/java/chat/rocket/android/widget/DividerItemDecoration.kt
  app/src/main/res/layout/item_chatroom_header.xml
Labels: :+1: improvement, :art: layout

#2155 [i18n] Update DE strings.xml
  app/src/main/res/values-de/strings.xml
Labels: :earth_americas: i18n

#2152 [I18N] Add traditional Chinese(zh-TW) translation file
  app/src/main/res/values-zh-rTW/strings.xml
Labels: :earth_americas: i18n

#2153 [I18N] Update RU strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#2159 [FIX] Cannot use multiple accounts
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/loginoptions/presentation/LoginOptionsPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/server/domain/AccountsRepository.kt
  app/src/main/java/chat/rocket/android/server/domain/GetAccountInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/RemoveAccountInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SaveAccountInteractor.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesAccountsRepository.kt
  app/src/main/res/layout/item_add_account.xml
Labels: :bug: bug

#2162 [IMPROVEMENT] Change message actions menu order.
  app/build.gradle
  app/src/main/java/chat/rocket/android/analytics/Analytics.kt
  app/src/main/java/chat/rocket/android/analytics/AnalyticsManager.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/BaseViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/res/menu/message_actions.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  app/src/play/java/chat/rocket/android/analytics/AnswersAnalytics.kt
  app/src/play/java/chat/rocket/android/analytics/GoogleAnalyticsForFirebase.kt
Labels: :+1: improvement

#2169 [I18N] Update RU strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#2134 [IMPROVEMENT] Set searchView width to max in ChatRoomFragment
  app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
Labels: :+1: improvement

#2173 [I18N] Adds Arabic translation
  app/src/main/res/values-ar/strings.xml
Labels: :earth_americas: i18n

#2175 [FIX] Video icon
  app/src/main/java/chat/rocket/android/chatdetails/ui/Menu.kt
  app/src/main/res/drawable/ic_video_white_24dp.xml
Labels: :art: layout

#2178 [CHORE] Update app version
  app/build.gradle
Labels: :truck: chore

#2180 [RELEASE] Merge BETA into MASTER
  app/build.gradle
Labels: :rocket: release:master

#2185 [CHORE] Update DEVELOP with MASTER
  app/build.gradle
  app/src/main/java/chat/rocket/android/analytics/Analytics.kt
  app/src/main/java/chat/rocket/android/analytics/AnalyticsManager.kt
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/loginoptions/presentation/LoginOptionsPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
  app/src/main/java/chat/rocket/android/chatdetails/ui/Menu.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/BaseViewHolder.kt
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/server/domain/AccountsRepository.kt
  app/src/main/java/chat/rocket/android/server/domain/GetAccountInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/RemoveAccountInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SaveAccountInteractor.kt
  app/src/main/java/chat/rocket/android/server/infraestructure/SharedPreferencesAccountsRepository.kt
  app/src/main/res/drawable/ic_video_white_24dp.xml
  app/src/main/res/layout/item_add_account.xml
  app/src/main/res/menu/message_actions.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  app/src/play/java/chat/rocket/android/analytics/AnswersAnalytics.kt
  app/src/play/java/chat/rocket/android/analytics/GoogleAnalyticsForFirebase.kt
Labels: :truck: chore

#2181 [i18n] Update DE Language
  app/src/main/res/values-de/strings.xml
Labels: :earth_americas: i18n
