Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2019-06, with the labels that each got.

#2328 [FIX] Fixes bottom sheets not being scrollable and completely visible
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/directory/ui/DirectorySortingBottomSheetFragment.kt
  app/src/main/java/chat/rocket/android/servers/ui/ServersBottomSheetFragment.kt
  app/src/main/java/chat/rocket/android/sortingandgrouping/ui/SortingAndGroupingBottomSheetFragment.kt
  app/src/main/res/layout/bottom_sheet_fragment_directory_sorting.xml
  app/src/main/res/layout/bottom_sheet_fragment_sort_by.xml
  app/src/main/res/values-ar/strings.xml
Labels: :bug: bug

#2337 [FIX] Messages rendering out of order bug
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#2352 [RELEASE] 3.4.2
  app/build.gradle
  app/src/main/java/chat/rocket/android/db/DatabaseManager.kt
  app/src/main/java/chat/rocket/android/server/infrastructure/ConnectionManager.kt
Labels: :rocket: release:master

#2327 [NEW] Implemented Webviews for Richmessages
  app/src/main/java/chat/rocket/android/chatroom/adapter/ChatRoomAdapter.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/bottomsheet/WebUrlBottomSheet.kt
  app/src/main/res/layout/webview_bottomsheet.xml
Labels: 🎉 feature

#2366 [I18N] Minor grammar improvements in german language file
  app/src/main/res/values-de/strings.xml
Labels: :earth_americas: i18n

#2378 [FIX] WebView not loading Privacy Policy and Terms of Service
  app/src/main/java/chat/rocket/android/webview/ui/WebViewActivity.kt
Labels: :bug: bug

#2384 [NEW] Add support for hardcoded server URL
  app/src/main/java/chat/rocket/android/authentication/server/ui/ServerFragment.kt
  app/src/main/java/chat/rocket/android/authentication/ui/AuthenticationActivity.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/res/values/defaults.xml
Labels: 🎉 feature

#2320 [FIX] Message search results (@mentions) do not have any date indication in the results
  app/src/main/java/chat/rocket/android/app/DateTimeHelper.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
Labels: :bug: bug

#2390 [IMPROVEMENT] Code improvement for #2320 PR
  app/src/main/java/chat/rocket/android/app/DateTimeHelper.kt
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Menu.kt
  app/src/main/java/chat/rocket/android/chatroom/uimodel/UiModelMapper.kt
Labels: :+1: improvement

#2087 [NEW] Add Option to view user profile avatar in fullscreen
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainNavigator.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/profile/ui/ImageProfileDialogFragment.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsPresenter.kt
  app/src/main/java/chat/rocket/android/userdetails/ui/UserDetailsFragment.kt
  app/src/main/res/drawable/ic_account_circle_black_24dp.xml
  app/src/main/res/layout/fragment_user_details.xml
  app/src/main/res/layout/image_profile_dialog_fragment.xml
  app/src/main/res/layout/update_avatar_options.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature
