Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2019-08, with the labels that each got.

#2441 [IMPROVEMENT] Add scroll to long text
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/res/layout/app_bar_chat_room.xml
Labels: :+1: improvement

#2453 [CHORE] Save token details
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/loginoptions/presentation/LoginOptionsPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt
  app/src/main/java/chat/rocket/android/authentication/signup/presentation/SignupPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/server/domain/model/Account.kt
  app/src/main/java/chat/rocket/android/servers/adapter/ServerViewHolder.kt
Labels: :truck: chore

#2429 [IMPROVEMENT] Add loading bar in Settings
  app/src/main/java/chat/rocket/android/settings/presentation/SettingsPresenter.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/res/layout/fragment_settings.xml
Labels: :+1: improvement

#2072 [BUG] Fix sending blank messages in reply and quote message.
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#2073 [IMPROVEMENT] Added save-discard dialog when editing user profile in ProfileFragment
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfileView.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/res/values/strings.xml
Labels: :+1: improvement

#2456 Update ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#2457 [FIX] Null Pointer Exception
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
Labels: :bug: bug

#2454 [RELEASE] Merge DEVELOP into BETA
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/loginoptions/presentation/LoginOptionsPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt
  app/src/main/java/chat/rocket/android/authentication/signup/presentation/SignupPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfileView.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/server/domain/model/Account.kt
  app/src/main/java/chat/rocket/android/servers/adapter/ServerViewHolder.kt
  app/src/main/java/chat/rocket/android/settings/presentation/SettingsPresenter.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/res/layout/app_bar_chat_room.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/values/strings.xml
Labels: :rocket: release:beta

#2459 [FIX] Unable to start a chat.
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
Labels: :bug: bug

#2458 [RELEASE] Merge BETA into MASTER
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/loginoptions/presentation/LoginOptionsPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt
  app/src/main/java/chat/rocket/android/authentication/signup/presentation/SignupPresenter.kt
  app/src/main/java/chat/rocket/android/authentication/twofactor/presentation/TwoFAPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/presentation/ChatRoomsPresenter.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt
  app/src/main/java/chat/rocket/android/profile/presentation/ProfileView.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/server/domain/model/Account.kt
  app/src/main/java/chat/rocket/android/servers/adapter/ServerViewHolder.kt
  app/src/main/java/chat/rocket/android/settings/presentation/SettingsPresenter.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/res/layout/app_bar_chat_room.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/values/strings.xml
Labels: :rocket: release:master

#2460 [CHORE] Release app version 2077 (3.5.1)
  .circleci/config.yml
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatinformation/ui/MessageInfoFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/domain/UriInteractor.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/Dialog.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/util/extensions/Intent.kt
  app/src/main/java/chat/rocket/android/util/extensions/Uri.kt
  build.gradle
  dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: :rocket: release:master
