Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2019-04, with the labels that each got.

#2201 [FIX] Typo in analytics message
  app/src/main/res/values/strings.xml
Labels: :+1: improvement

#2198 [BUG] Check and Request camera permission before taking photos.
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/helper/AndroidPermissionsHelper.kt
  app/src/main/java/chat/rocket/android/helper/ImageHelper.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: :bug: bug

#2231 [FIX] Fixed profile avatar not updating when changed
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/java/chat/rocket/android/userdetails/ui/UserDetailsFragment.kt
  app/src/main/res/layout/avatar_profile.xml
  app/src/main/res/layout/fragment_preferences.xml
  app/src/main/res/layout/fragment_settings.xml
Labels: :bug: bug

#2226 [CHORE] Update Jitsi library version
  app/src/main/java/chat/rocket/android/videoconference/ui/VideoConferenceActivity.kt
  dependencies.gradle
Labels: :truck: chore

#2200 [BUG] Solves the favorite icon not being shown.
  app/src/main/java/chat/rocket/android/chatdetails/ui/Menu.kt
Labels: :bug: bug

#2188 [IMPROVEMENT] Support RTL layout on editing message action bar
  app/src/main/res/layout/message_action_bar.xml
Labels: :+1: improvement

#2214 [FIX] Typos and Translation Mistakes
  app/src/main/java/chat/rocket/android/authentication/loginoptions/presentation/LoginOptionsView.kt
  app/src/main/java/chat/rocket/android/helper/OauthHelper.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
  app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/res/layout/fragment_authentication_log_in.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: :+1: improvement

#2237 [I18N] Update RU strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#2239 [BUG] ScrollView was not scrolling to bottom of screen.
  app/src/main/res/layout/fragment_settings.xml
Labels: :art: layout, :bug: bug

#2247 [i18n] Update german strings.
  app/src/main/res/values-de/strings.xml
Labels: :earth_americas: i18n

#2261 [FIX] Typo in JitsiHelper.kt
  app/src/main/java/chat/rocket/android/helper/JitsiHelper.kt
Labels: :+1: improvement

#2260 [FIX] Sorting issue in ChatRoomDao.kt
  app/src/main/java/chat/rocket/android/db/ChatRoomDao.kt
Labels: :bug: bug

#2241 [FIX] Removes @ from mentions.
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
Labels: :+1: improvement

#2236 [FIX] Listen to favorite changes
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#2191 [IMPROVEMENT] Adds animation when expanding/collapsing the login options
  app/src/main/java/chat/rocket/android/authentication/loginoptions/ui/LoginOptionsFragment.kt
Labels: :+1: improvement, :art: layout

#2244 [IMPROVEMENT] Changes status title
  app/src/main/res/layout/fragment_user_details.xml
  app/src/main/res/values/strings.xml
Labels: :+1: improvement

#2262 [NEW] Change app language
  app/src/main/java/chat/rocket/android/core/behaviours/AppLanguageView.kt
  app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
  app/src/main/java/chat/rocket/android/main/di/MainModule.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainPresenter.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/server/domain/GetCurrentLanguageInteractor.kt
  app/src/main/java/chat/rocket/android/server/domain/SaveCurrentLanguageInteractor.kt
  app/src/main/java/chat/rocket/android/server/infrastructure/CurrentLanguageRepository.kt
  app/src/main/java/chat/rocket/android/server/infrastructure/SharedPrefsCurrentLanguageRepository.kt
  app/src/main/java/chat/rocket/android/settings/presentation/SettingsPresenter.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 feature

#2265 [I18N] Update RU strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#2269 [FIX] Fixes Take Photo from crashing in ProfileFragment
  app/src/main/java/chat/rocket/android/helper/AndroidPermissionsHelper.kt
  app/src/main/java/chat/rocket/android/profile/ui/ProfileFragment.kt
Labels: :bug: bug

#2263 [NEW] Sort chats by unread on top.
  app/src/main/java/chat/rocket/android/chatrooms/infrastructure/ChatRoomsRepository.kt
  app/src/main/java/chat/rocket/android/chatrooms/ui/ChatRoomsFragment.kt
  app/src/main/java/chat/rocket/android/chatrooms/viewmodel/ChatRoomsViewModel.kt
  app/src/main/java/chat/rocket/android/db/ChatRoomDao.kt
Labels: 🎉 feature
