Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2019-01, with the labels that each got.

#1972 [CHORE] Update README.md
  README.md
Labels: :truck: chore

#1984 [FIX] Mention autocomplete stops working
  suggestions/src/main/java/chat/rocket/android/suggestions/ui/SuggestionsView.kt
Labels: :bug: bug

#1968 [I18N] Update Brazilian language translations
  app/src/main/res/values-pt-rBR/strings.xml
Labels: :earth_americas: i18n

#1986 [RELEASE] Merge DEVELOP into BETA
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values/strings.xml
  suggestions/src/main/java/chat/rocket/android/suggestions/ui/SuggestionsView.kt
Labels: :rocket: release:beta

#1988 [FIX] Typing status
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: :bug: bug

#1989 [FIX] Settings menu
  app/build.gradle
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: :bug: bug

#1993 [I18N] Chinese translation
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: :earth_americas: i18n

#1998 [IMPROVEMENT] Avoid closing the app from some screens.
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
Labels: :+1: improvement

#1985 [I18N] Add Persian language
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
  app/src/main/java/chat/rocket/android/members/ui/MembersFragment.kt
  app/src/main/java/chat/rocket/android/util/HttpLoggingInterceptor.kt
  app/src/main/res/layout/file_attachments_dialog.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: :earth_americas: i18n
