Repository RocketChat/Rocket.Chat.Android, pull requests merged in 2019-05, with the labels that each got.

#2286 [FIX] Fixes compound drawables being set to the incorrect direction in RTL languages
  app/src/main/java/chat/rocket/android/app/DrawableHelper.kt
  app/src/main/java/chat/rocket/android/authentication/registerusername/ui/RegisterUsernameFragment.kt
  app/src/main/java/chat/rocket/android/chatdetails/ui/ChatDetailsFragment.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomActivity.kt
  app/src/main/java/chat/rocket/android/directory/ui/DirectoryFragment.kt
  app/src/main/java/chat/rocket/android/directory/ui/DirectorySortingBottomSheetFragment.kt
  app/src/main/java/chat/rocket/android/sortingandgrouping/ui/SortingAndGroupingBottomSheetFragment.kt
Labels: :bug: bug

#2300 [FIX] Typo fixed in MainActivity.kt
  app/src/main/java/chat/rocket/android/main/ui/MainActivity.kt
Labels: :+1: improvement

#2296 [FIX][IMPROVEMENT] Fixes layout issues
  app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomViewHolder.kt
  app/src/main/java/chat/rocket/android/directory/ui/DirectorySortingBottomSheetFragment.kt
  app/src/main/res/drawable/bg_empty_user_avatar.xml
  app/src/main/res/drawable/ic_action_message_info_outline_24dp.xml
  app/src/main/res/drawable/ic_app_name.xml
  app/src/main/res/drawable/ic_arrow_back_white_24dp.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_camera_24dp.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_check_read_24dp.xml
  app/src/main/res/drawable/ic_check_unread_24dp.xml
  app/src/main/res/drawable/ic_hashtag_16dp.xml
  app/src/main/res/drawable/ic_lock_12_dp.xml
  app/src/main/res/drawable/ic_unread_20dp.xml
  app/src/main/res/drawable/ic_user_16dp.xml
  app/src/main/res/drawable/image_dummy.xml
  app/src/main/res/drawable/message_reply_button_bg.xml
  app/src/main/res/drawable/round_textview.xml
  app/src/main/res/layout/app_bar_password.xml
  app/src/main/res/layout/bottom_sheet_fragment_directory_sorting.xml
  app/src/main/res/layout/emoji_image_row_item.xml
  app/src/main/res/layout/fragment_authentication_on_boarding.xml
  app/src/main/res/layout/fragment_authentication_server.xml
  app/src/main/res/layout/fragment_chat_details.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/item_actions_attachment.xml
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/message_attachment_options.xml
  app/src/main/res/layout/unread_messages_badge.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/styles.xml
  draw/src/main/res/drawable/circle_green.xml
  emoji/src/main/res/drawable/ic_backspace_gray_24dp.xml
Labels: :+1: improvement, :bug: bug

#2293 [IMPROVEMENT] Sorting on directory is applied immediately when checked.
  app/src/main/java/chat/rocket/android/directory/ui/DirectorySortingBottomSheetFragment.kt
Labels: :+1: improvement

#2303 [I18N] Update RU strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
Labels: :earth_americas: i18n

#2271 [NEW] Typing +:emoji_name: reacts to last message
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: 🎉 feature

#2314 [i18n] Update Strings.xml
  app/src/main/res/values-de/strings.xml
Labels: :earth_americas: i18n

#2268 [IMPROVEMENT] Let language setter show the selected locale
  app/src/main/java/chat/rocket/android/server/infrastructure/SharedPrefsCurrentLanguageRepository.kt
  app/src/main/java/chat/rocket/android/settings/presentation/SettingsPresenter.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
Labels: :+1: improvement

#2304 [FIX][IMPROVEMENT][I18N] Adds support for RTL ViewPager for RTL languages
  app/src/main/java/chat/rocket/android/app/DrawableHelper.kt
  app/src/main/res/drawable/ic_send_24dp.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-ru-rRU/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  draw/src/main/res/drawable/ic_send_black_24dp.xml
  emoji/src/main/java/chat/rocket/android/emoji/EmojiKeyboardPopup.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiPickerPopup.kt
  emoji/src/main/java/chat/rocket/android/emoji/EmojiViewPager.kt
  emoji/src/main/res/drawable/ic_backspace_gray_24dp.xml
  emoji/src/main/res/layout-land/emoji_picker.xml
  emoji/src/main/res/layout/emoji_picker.xml
Labels: :+1: improvement, :bug: bug, :earth_americas: i18n

#2273 [FIX] Fixes unable to see other User profile details
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsPresenter.kt
  app/src/main/java/chat/rocket/android/userdetails/presentation/UserDetailsView.kt
  app/src/main/java/chat/rocket/android/userdetails/ui/UserDetailsFragment.kt
  app/src/main/res/layout/fragment_user_details.xml
Labels: :bug: bug

#2212 [NEW] Swipe to reply message
  app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt
Labels: 🎉 feature

#2071 [FIX][LAYOUT] Margin on bottom of profile fragment
  app/src/main/res/layout/fragment_profile.xml
Labels: :art: layout, :bug: bug

#2084 [IMPROVEMENT] Hide the drawing toolbar while drawing
  app/build.gradle
  draw/src/main/java/chat/rocket/android/draw/main/ui/DrawActivity.kt
  draw/src/main/java/chat/rocket/android/draw/widget/CustomDrawView.kt
Labels: :+1: improvement

#2082 [IMPROVEMENT] Listen to changes on user avatar.
  app/src/main/java/chat/rocket/android/db/DatabaseManager.kt
  app/src/main/java/chat/rocket/android/db/DatabaseManagerFactory.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: :+1: improvement

#2017 [BUG] Fixes custom emoji alias rendering issue
  emoji/build.gradle
  emoji/src/main/java/chat/rocket/android/emoji/EmojiParser.kt
Labels: :bug: bug

#2032 [BUG] Fixes Drawing cleared on orientation change issue
  draw/src/main/AndroidManifest.xml
Labels: :bug: bug

#2309 [FIX] Add a reaction not working/Chat list not showing/Chat list not updating/
  app/build.gradle
  app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt
  app/src/main/java/chat/rocket/android/chatrooms/domain/FetchChatRoomsInteractor.kt
  build.gradle
  dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: :bug: bug

#2080 [IMPROVEMENT][LAYOUT] Profile Layout according to a web interface
  app/build.gradle
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: :+1: improvement, :art: layout

#2321 [RELEASE] 3.4.1
  app/build.gradle
Labels: :rocket: release:master

#2334 [FIX] Fixes issues and memory leaks after changing language
  app/src/main/java/chat/rocket/android/directory/presentation/DirectoryPresenter.kt
  app/src/main/java/chat/rocket/android/directory/ui/DirectoryFragment.kt
  app/src/main/java/chat/rocket/android/main/presentation/MainNavigator.kt
  app/src/main/java/chat/rocket/android/settings/presentation/SettingsPresenter.kt
  app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt
Labels: :bug: bug

#2345 [FIX] SAML: Save username on login
  app/src/main/java/chat/rocket/android/authentication/loginoptions/presentation/LoginOptionsPresenter.kt
Labels: :bug: bug

#2335 [i18n] Fix wrong String
  app/src/main/res/values-de/strings.xml
Labels: :earth_americas: i18n

#2353 [FIX] Channel Freeze Issue
  app/src/main/java/chat/rocket/android/helper/MessageParser.kt
Labels: :bug: bug

#2343 [I18N] Update french translations
  app/src/main/res/values-fr/strings.xml
Labels: :earth_americas: i18n
